In [3]:
import polars as pl

In [5]:
df = pl.read_parquet("data/cnb_vyber.parquet")

In [9]:
df.sample(10)

shape: (10, 62)
┌──────────────┬──────────────┬──────────────┬─────────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ 008          ┆ 020_a        ┆ 020_c        ┆ 020_q       ┆ … ┆ 928_a       ┆ 964_a       ┆ leader      ┆ 001         │
│ ---          ┆ ---          ┆ ---          ┆ ---         ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ str          ┆ list[str]    ┆ list[str]    ┆ list[str]   ┆   ┆ list[str]   ┆ list[str]   ┆ str         ┆ str         │
╞══════════════╪══════════════╪══════════════╪═════════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 990614s1936  ┆ null         ┆ null         ┆ null        ┆ … ┆ null        ┆ null        ┆ nam a22     ┆ bk193606049 │
│ xr           ┆              ┆              ┆             ┆   ┆             ┆             ┆ 1  4500     ┆             │
│ …            ┆              ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
│ 170102s2016  ┆ ["978-80-867 ┆ null         ┆ ["(brožován ┆ … ┆ null        ┆ null        ┆ cam a22     ┆ nkc20172878 │
│ xr ach e     ┆ 51-31-3"]    ┆              ┆ o)"]        ┆   ┆             ┆             ┆ i 4500      ┆ 049         │
│ 1…           ┆              ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
│ 001031s1910  ┆ null         ┆ null         ┆ null        ┆ … ┆ null        ┆ null        ┆ nam a22     ┆ nos19023540 │
│ xr           ┆              ┆              ┆             ┆   ┆             ┆             ┆ 1  4500     ┆ 8001        │
│ …            ┆              ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
│ 990616s1999  ┆ ["80-240-100 ┆ ["Kč 22,90"] ┆ ["(brož.)   ┆ … ┆ null        ┆ null        ┆ nam a22     ┆ cpk19990663 │
│ xr     e     ┆ 5-4"]        ┆              ┆ :"]         ┆   ┆             ┆             ┆ a 4500      ┆ 047         │
│ 0…           ┆              ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
│ 990908s1999  ┆ ["80-243-011 ┆ ["Kč 25,00"] ┆ ["(brož.)   ┆ … ┆ null        ┆ null        ┆ cam a22     ┆ cpk20010705 │
│ xr     e     ┆ 2-1"]        ┆              ┆ :"]         ┆   ┆             ┆             ┆ a 4500      ┆ 959         │
│ 0…           ┆              ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
│ 160712s2016  ┆ ["978-80-741 ┆ null         ┆ ["(vázáno)" ┆ … ┆ null        ┆ null        ┆ cam a22     ┆ nkc20162825 │
│ xr h   e c   ┆ 5-131-6"]    ┆              ┆ ]           ┆   ┆             ┆             ┆ i 4500      ┆ 060         │
│ 0…           ┆              ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
│ 091130s1952  ┆ null         ┆ null         ┆ ["(Brož.)"] ┆ … ┆ ["Státní    ┆ null        ┆ nam a22     ┆ nkc20092007 │
│ xr     f     ┆              ┆              ┆             ┆   ┆ knihovna    ┆             ┆ a 4500      ┆ 954         │
│ 0…           ┆              ┆              ┆             ┆   ┆ společenský ┆             ┆             ┆             │
│              ┆              ┆              ┆             ┆   ┆ c…          ┆             ┆             ┆             │
│ 160309s2015  ┆ ["978-80-870 ┆ null         ┆ ["(vázáno)" ┆ … ┆ ["Periskop" ┆ null        ┆ nam a22     ┆ nkc20162783 │
│ xr a   g     ┆ 77-33-7"]    ┆              ┆ ]           ┆   ┆ ]           ┆             ┆ i 4500      ┆ 290         │
│ 0…           ┆              ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
│ 970123s1970  ┆ null         ┆ ["Kčs        ┆ ["(Váz.)    ┆ … ┆ null        ┆ ["Umění     ┆ nam a22     ┆ bk197100055 │
│ xr aefh      ┆              ┆ 135,00"]     ┆ :"]         ┆   ┆             ┆ výtvarné    ┆ a 4500      ┆             │
│ 0…           ┆              ┆              ┆             ┆   ┆             ┆ gotické     ┆             ┆             │
│              ┆              ┆              ┆             ┆   ┆             ┆ české…      ┆             ┆             │
│ 100726s1981  ┆ null         ┆ ["Kčs 8,00"] ┆ ["(Brož.)   ┆ … ┆ null        ┆ null        ┆ nam a22     ┆ nkc20102114 │
│ xr a   e f   ┆              ┆              ┆ :"]         ┆   ┆             ┆             ┆ a 4500      ┆ 380         │
│ 0…           ┆              ┆              ┆             ┆   ┆             ┆             ┆             ┆             │
└──────────────┴──────────────┴──────────────┴─────────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

In [25]:
len(df.select(pl.col(["072_a","072_x"])).explode(["072_a","072_x"]).drop_nulls().unique())

638

In [23]:
df.select(pl.col(["072_a","072_x"])).explode(["072_a","072_x"]).drop_nulls().unique().sample(10)

shape: (10, 2)
┌─────────────────┬─────────────────────────────────┐
│ 072_a           ┆ 072_x                           │
│ ---             ┆ ---                             │
│ str             ┆ str                             │
╞═════════════════╪═════════════════════════════════╡
│ 780.92          ┆ Persons associated with music   │
│ 811.34          ┆ Vymřelé jazyky neznámé klasifi… │
│ 94(46)          ┆ Dějiny států a území na Pyrene… │
│ 683             ┆ Železářství. Zámečnictví. Topn… │
│ 780.901-780.905 ┆ Periods of stylistic developme… │
│ 154             ┆ Subconscious and altered state… │
│ 791             ┆ Film. Cirkus. Lidová zábava     │
│ 316.36          ┆ Manželství a rodina. Sexuální … │
│ 21              ┆ Prehistorická a primitivní náb… │
│ 316.77          ┆ Informační věda                 │
└─────────────────┴─────────────────────────────────┘

In [ ]:
df.select(pl.col(["072_a","072_x"])).explode(["072_a","072_x"]).drop_nulls().unique().write_csv('data/temata_czen.csv')

In [17]:
nulaosmdesat = pl.read_parquet("data/cnb_sloupce/080.parquet")

In [19]:
nulaosmdesat

shape: (1_032_857, 5)
┌─────────────────────────────────┬───────────────────────────────┬───────┬───────────┬────────────────┐
│ 080_a                           ┆ 080_2                         ┆ 080_x ┆ 080_ind1  ┆ 001            │
│ ---                             ┆ ---                           ┆ ---   ┆ ---       ┆ ---            │
│ list[str]                       ┆ list[str]                     ┆ str   ┆ list[str] ┆ str            │
╞═════════════════════════════════╪═══════════════════════════════╪═══════╪═══════════╪════════════════╡
│ ["352/353", "338.46"]           ┆ ["undef", "undef"]            ┆ null  ┆ null      ┆ ck8300078      │
│ ["339.923", "338.45"]           ┆ ["undef", "undef"]            ┆ null  ┆ null      ┆ ck8300080      │
│ ["339.923"]                     ┆ ["undef"]                     ┆ null  ┆ null      ┆ ck8300081      │
│ ["343.3/.7", "343", … "(082)"]  ┆ ["MRF", "MRF", … "MRF"]       ┆ null  ┆ null      ┆ ck8300082      │
│ ["347", "349", … "343"]         ┆ ["undef", "undef", … "undef"] ┆ null  ┆ null      ┆ ck8300083      │
│ …                               ┆ …                             ┆ …     ┆ …         ┆ …              │
│ ["316.346.32-053.5", "394", … … ┆ ["MRF", "MRF", … "MRF"]       ┆ null  ┆ null      ┆ cpg20253674064 │
│ ["316.346.32-053.5", "394", … … ┆ ["MRF", "MRF", … "MRF"]       ┆ null  ┆ null      ┆ cpg20253674065 │
│ ["316.346.32-053.5", "394", … … ┆ ["MRF", "MRF", … "MRF"]       ┆ null  ┆ null      ┆ cpg20253674066 │
│ ["663.813", "(084.5)659.1"]     ┆ ["MRF", "MRF"]                ┆ null  ┆ null      ┆ cpg20253674067 │
│ ["663.81", "(084.5)659.1"]      ┆ ["MRF", "MRF"]                ┆ null  ┆ null      ┆ cpg20253674069 │
└─────────────────────────────────┴───────────────────────────────┴───────┴───────────┴────────────────┘

In [21]:
nulaosmdesat.filter(~pl.col('080_x').is_null())

shape: (5, 5)
┌────────────────┬───────────┬───────────┬───────────┬────────────────┐
│ 080_a          ┆ 080_2     ┆ 080_x     ┆ 080_ind1  ┆ 001            │
│ ---            ┆ ---       ┆ ---       ┆ ---       ┆ ---            │
│ list[str]      ┆ list[str] ┆ str       ┆ list[str] ┆ str            │
╞════════════════╪═══════════╪═══════════╪═══════════╪════════════════╡
│ ["913"]        ┆ ["MRF"]   ┆ (437.6)   ┆ null      ┆ nos190135946   │
│ ["502:912.43"] ┆ ["MRF"]   ┆ (437.316) ┆ null      ┆ cpc20142633715 │
│ ["502:912.43"] ┆ ["MRF"]   ┆ (437.315) ┆ null      ┆ cpc20142633876 │
│ ["502:912.43"] ┆ ["MRF"]   ┆ (437.315) ┆ null      ┆ cpc20142633880 │
│ ["550:912.43"] ┆ ["MRF"]   ┆ (437.315) ┆ null      ┆ cpc20142633922 │
└────────────────┴───────────┴───────────┴───────────┴────────────────┘

In [27]:
sestsetpadesat = pl.read_parquet("data/cnb_sloupce/650.parquet")

In [35]:
sestsetpadesat.drop_nulls().sample(10)

shape: (10, 9)
┌──────────────┬──────────────┬──────────────┬─────────────┬───┬─────────────┬─────────────┬─────────────┬─────────────┐
│ 650_ind1     ┆ 650_ind2     ┆ 650_a        ┆ 650_7       ┆ … ┆ 650_x       ┆ 650_z       ┆ 650_y       ┆ 001         │
│ ---          ┆ ---          ┆ ---          ┆ ---         ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ list[str]    ┆ list[str]    ┆ list[str]    ┆ list[str]   ┆   ┆ list[str]   ┆ list[str]   ┆ list[str]   ┆ str         │
╞══════════════╪══════════════╪══════════════╪═════════════╪═══╪═════════════╪═════════════╪═════════════╪═════════════╡
│ ["0", "0", … ┆ ["7", "7", … ┆ ["režisérky" ┆ ["ph871606" ┆ … ┆ [null,      ┆ ["Česko",   ┆ ["20.-21.   ┆ nkc20172958 │
│ "0"]         ┆ "9"]         ┆ ,            ┆ ,           ┆   ┆ null, …     ┆ "Česko", …  ┆ století",   ┆ 439         │
│              ┆              ┆ "hudebníci", ┆ "ph117204", ┆   ┆ null]       ┆ "Czechia"…  ┆ "20.-21. s… ┆             │
│              ┆              ┆ … "…         ┆ … nul…      ┆   ┆             ┆             ┆             ┆             │
│ ["0", "0", … ┆ ["7", "7", … ┆ ["šlechta",  ┆ ["ph116832" ┆ … ┆ [null, "spo ┆ ["Česko",   ┆ ["15.-16.   ┆ nkc20132522 │
│ "0"]         ┆ "9"]         ┆ "šlechta", … ┆ ,           ┆   ┆ lečenské    ┆ null, …     ┆ století",   ┆ 698         │
│              ┆              ┆ "self…       ┆ "ph116832", ┆   ┆ postavení"… ┆ "Czechia"]  ┆ null, … "1… ┆             │
│              ┆              ┆              ┆ … nul…      ┆   ┆             ┆             ┆             ┆             │
│ ["0", "0", … ┆ ["7", "7", … ┆ ["čeští      ┆ ["ph128168" ┆ … ┆ [null,      ┆ [null,      ┆ ["20.       ┆ cpk20051492 │
│ "0"]         ┆ "9"]         ┆ básníci",    ┆ ,           ┆   ┆ "partnerské ┆ null, …     ┆ století",   ┆ 326         │
│              ┆              ┆ "čeští       ┆ "ph128168", ┆   ┆ a rodinné   ┆ "Czechia"]  ┆ null, …     ┆             │
│              ┆              ┆ básní…       ┆ … nul…      ┆   ┆ v…          ┆             ┆ "20th-…     ┆             │
│ ["0", "0", … ┆ ["7", "7", … ┆ ["cestovatel ┆ ["ph119109" ┆ … ┆ [null,      ┆ ["Česko",   ┆ ["20.-21.   ┆ nkc20243596 │
│ "0"]         ┆ "9"]         ┆ é", "cestova ┆ ,           ┆   ┆ "přátelé a  ┆ null, …     ┆ století",   ┆ 252         │
│              ┆              ┆ telé",…      ┆ "ph119109", ┆   ┆ spolupracov ┆ null]       ┆ null, … nu… ┆             │
│              ┆              ┆              ┆ … nul…      ┆   ┆ n…          ┆             ┆             ┆             │
│ ["0", "0", … ┆ ["7", "7", … ┆ ["herečky",  ┆ ["ph120685" ┆ … ┆ [null,      ┆ ["Česko",   ┆ ["20.-21.   ┆ nkc20102126 │
│ "0"]         ┆ "9"]         ┆ "herečky", … ┆ ,           ┆   ┆ "dětství",  ┆ null, …     ┆ století",   ┆ 288         │
│              ┆              ┆ "actr…       ┆ "ph120685", ┆   ┆ …           ┆ null]       ┆ null, … nu… ┆             │
│              ┆              ┆              ┆ … nul…      ┆   ┆ "childhood… ┆             ┆             ┆             │
│ ["0", "0", … ┆ ["7", "7", … ┆ ["katedrály" ┆ ["ph114888" ┆ … ┆ [null,      ┆ ["Česko",   ┆ [null,      ┆ nkc20162798 │
│ "0"]         ┆ "9"]         ┆ ,            ┆ ,           ┆   ┆ "dějiny", … ┆ null, …     ┆ null, …     ┆ 837         │
│              ┆              ┆ "katedrály", ┆ "ph114888", ┆   ┆ null]       ┆ "Czechia"]  ┆ "14th-20th  ┆             │
│              ┆              ┆ … "…         ┆ … nul…      ┆   ┆             ┆             ┆ cent…       ┆             │
│ ["0", "0", … ┆ ["7", "7", … ┆ ["překlady", ┆ ["ph124902" ┆ … ┆ [null,      ┆ [null,      ┆ ["3.        ┆ cpk20021174 │
│ "0"]         ┆ "9"]         ┆ "překlady do ┆ ,           ┆   ┆ null, …     ┆ null, …     ┆ století př. ┆ 866         │
│              ┆              ┆ češt…        ┆ "ph124901", ┆   ┆ "Early      ┆ null]       ┆ Kr.-20.     ┆             │
│              ┆              ┆              ┆ … nul…      ┆   ┆ works to…   ┆             ┆ stole…      ┆             │
│ ["0", "0", … ┆ ["7", "7", … ┆ ["templáři", ┆ ["ph126532" ┆ … ┆ ["dějiny",  ┆ [null,      ┆ [null,      ┆ nkc20092024 │
│ "0"]         ┆ "9"]         ┆ "templáři",  ┆ ,           ┆   ┆ null, …     ┆ "Česko", …  ┆ "13.-14.    ┆ 831         │
│              ┆              ┆ … "hi…       ┆ "ph126532", ┆   ┆ null]       ┆ "Czechia"]  ┆ století", … ┆             │
│              ┆              ┆              ┆ … nul…      ┆   ┆             ┆             ┆ nu…         ┆             │
│ ["0", "0", … ┆ ["7", "7", … ┆ ["covid-19", ┆ ["ph1075649 ┆ … ┆ [null,      ┆ [null,      ┆ [null, "21. ┆ nkc20213344 │
│ "0"]         ┆ "9"]         ┆ "pandemie",  ┆ ",          ┆   ┆ null, …     ┆ null, …     ┆ století", … ┆ 299         │
│              ┆              ┆ … "in…       ┆ "ph330262", ┆   ┆ null]       ┆ "Czechia"]  ┆ "21st …     ┆             │
│              ┆              ┆              ┆ … nu…       ┆   ┆             ┆             ┆             ┆             │
│ ["0", "0", … ┆ ["7", "7", … ┆ ["Němci",    ┆ ["ph117943" ┆ … ┆ [null,      ┆ ["Českoslov ┆ [null,      ┆ nkc20081833 │
│ "0"]         ┆ "9"]         ┆ "nacismus a  ┆ ,           ┆   ┆ null, …     ┆ ensko",     ┆ null, …     ┆ 618         │
│              ┆              ┆ ženy", ……    ┆ "ph221979", ┆   ┆ null]       ┆ null, …     ┆ null]       ┆             │
│              ┆              ┆              ┆ … nul…      ┆   ┆             ┆ nul…        ┆             ┆             │
└──────────────┴──────────────┴──────────────┴─────────────┴───┴─────────────┴─────────────┴─────────────┴─────────────┘

In [43]:
sestsetpadesat.drop_nulls().select(pl.col(["650_a","650_7","650_2"])).explode(["650_a","650_7","650_2"]).filter(pl.col("650_2") == "czenas").unique().select(pl.col(["650_a","650_7"]))

shape: (5_493, 2)
┌────────────────────────┬──────────┐
│ 650_a                  ┆ 650_7    │
│ ---                    ┆ ---      │
│ str                    ┆ str      │
╞════════════════════════╪══════════╡
│ prezidentské volby     ┆ ph115883 │
│ měšťanská rodina       ┆ ph123116 │
│ scénografie            ┆ ph116114 │
│ rozvoj venkova         ┆ ph136666 │
│ cisterciácké kláštery  ┆ ph119244 │
│ …                      ┆ …        │
│ vysokoškolské studium  ┆ ph127279 │
│ kati                   ┆ ph121522 │
│ soukromí zemědělci     ┆ ph125876 │
│ architektonický design ┆ ph114079 │
│ hra na klavír          ┆ ph135165 │
└────────────────────────┴──────────┘

In [47]:
sestsetpadesat.drop_nulls().select(pl.col(["650_a","650_7","650_2"])).explode(["650_a","650_7","650_2"]).filter(pl.col("650_2") == "czenas").unique().select(pl.col(["650_a","650_7"])).write_csv('data/temata_czenas.csv')