In [1]:
import os
import polars as pl
from src.bez_bordelu import bez_bordelu
from src.najdi_rok import najdi_rok
from src.pocet_stran import pocet_stran
pl.Config(tbl_rows=500)

In [3]:
df = pl.read_parquet(
    os.path.join("data","cnb_vyber.parquet")
).with_columns(
    pl.col('300_a').map_elements(pocet_stran, return_dtype=int).alias('stran')
).with_columns(
    pl.col('008').map_elements(najdi_rok, return_dtype=int).alias('rok')
).with_columns(
    pl.col('245_a').map_elements(bez_bordelu, return_dtype=str)
)

In [4]:
df.filter(pl.col("245_a").str.contains("Co je uvnitř"))

shape: (1, 64)
┌───────────────────────────┬───────────┬───────────┬───────────┬───┬─────────────────────┬─────────────┬───────┬──────┐
│ 008                       ┆ 020_a     ┆ 020_c     ┆ 020_q     ┆ … ┆ leader              ┆ 001         ┆ stran ┆ rok  │
│ ---                       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---                 ┆ ---         ┆ ---   ┆ ---  │
│ str                       ┆ list[str] ┆ list[str] ┆ list[str] ┆   ┆ str                 ┆ str         ┆ i64   ┆ i64  │
╞═══════════════════════════╪═══════════╪═══════════╪═══════════╪═══╪═════════════════════╪═════════════╪═══════╪══════╡
│ 971002s1968    xr         ┆ null      ┆ null      ┆ null      ┆ … ┆ nam a22     1  4500 ┆ bk196902797 ┆ 66    ┆ 1968 │
│ …                         ┆           ┆           ┆           ┆   ┆                     ┆             ┆       ┆      │
└───────────────────────────┴───────────┴───────────┴───────────┴───┴─────────────────────┴─────────────┴───────┴──────┘

In [9]:
df.explode("700_7").filter(pl.col("700_7") == "jk01102794").select(pl.col(['rok','100_a','245_a'])).sort(by='rok')

shape: (70, 3)
┌──────┬───────────────────────────────┬─────────────────────────────────┐
│ rok  ┆ 100_a                         ┆ 245_a                           │
│ ---  ┆ ---                           ┆ ---                             │
│ i64  ┆ str                           ┆ str                             │
╞══════╪═══════════════════════════════╪═════════════════════════════════╡
│ 1950 ┆ Kohout, Pavel,                ┆ O černém a bílém                │
│ 1951 ┆ Il‘jin, M.,                   ┆ Sto tisíc proč                  │
│ 1953 ┆ Beljakov, A. P.               ┆ Elektřina kolem nás             │
│ 1953 ┆ Hladký, Miroslav,             ┆ Jak dělat výlety                │
│ 1954 ┆ Perel'man, Jakov Isidorovič,  ┆ Zajímavá geometrie              │
│ 1955 ┆ Il‘jin, M.,                   ┆ Sto tisíc proč                  │
│ 1956 ┆ Lem, Stanisław,               ┆ Astronauti                      │
│ 1956 ┆ Lem, Stanisław,               ┆ K mrakům Magellanovým           │
│ 1958 ┆ Sedláček, Jiří                ┆ Kajak papírák                   │
│ 1958 ┆ Lem, Stanisław,               ┆ K mrakům Magellanovým           │
│ 1958 ┆ Martynov, Georgij Sergejevič, ┆ Reportáž z Marsu                │
│ 1962 ┆ Běhounek, František,          ┆ Akce L                          │
│ 1963 ┆ null                          ┆ Přírodopis pro 9. ročník zákla… │
│ 1965 ┆ Codr, Milan,                  ┆ Hvězdné povolání                │
│ 1965 ┆ null                          ┆ Přírodopis pro 9. ročník zákla… │
│ 1965 ┆ Král, František               ┆ Zabraňte požárům!               │
│ 1965 ┆ Čapek, Karel,                 ┆ Válka s Mloky                   │
│ 1966 ┆ Lem, Stanisław,               ┆ Astronauti                      │
│ 1966 ┆ Běhounek, František,          ┆ Robinzoni vesmíru               │
│ 1967 ┆ Souček, Ludvík,               ┆ Velké otazníky                  │
│ 1968 ┆ null                          ┆ Přírodopis pro 9. ročník zákla… │
│ 1968 ┆ Doubek, Jan                   ┆ Co je uvnitř?                   │
│ 1969 ┆ null                          ┆ Přírodopis pro 9. ročník zákla… │
│ 1971 ┆ null                          ┆ Přírodopis pro 9. ročník zákla… │
│ 1972 ┆ Běhounek, František,          ┆ Akce L                          │
│ 1972 ┆ null                          ┆ Přírodopis pro 9. ročník zákla… │
│ 1973 ┆ null                          ┆ Přírodopis pro 9. ročník zákla… │
│ 1973 ┆ Říha, Bohumil,                ┆ Vlastivěda pro 5. ročník zákla… │
│ 1973 ┆ Říha, Bohumil,                ┆ Vlastivěda pro 5. ročník zákla… │
│ 1974 ┆ null                          ┆ Přírodopis pro 9. ročník zákla… │
│ 1974 ┆ Říha, Bohumil,                ┆ Vlastivěda pro 5. ročník zákla… │
│ 1975 ┆ Říha, Bohumil,                ┆ Vlastivěda pro 5. ročník zákla… │
│ 1975 ┆ null                          ┆ Přírodopis pro 9. ročník zákla… │
│ 1976 ┆ Říha, Bohumil,                ┆ Vlastivěda pro 5. ročník zákla… │
│ 1976 ┆ null                          ┆ Přírodopis pro 9. ročník zákla… │
│ 1977 ┆ null                          ┆ Přírodopis pro 9. ročník zákla… │
│ 1978 ┆ null                          ┆ Přírodopis pro 9. ročník zákla… │
│ 1978 ┆ Říha, Bohumil,                ┆ Vlastivěda pro 5. ročník zákla… │
│ 1979 ┆ Scortia, Thomas N.,           ┆ Prométheus v plamenech          │
│ 1979 ┆ null                          ┆ Přírodopis pro 9. ročník zákla… │
│ 1980 ┆ null                          ┆ Neviditelní zloději             │
│ 1980 ┆ null                          ┆ Přírodopis pro 9. ročník zákla… │
│ 1982 ┆ Moravec, Miroslav,            ┆ Stanice u Moře dešťů            │
│ 1983 ┆ Kettner, Petr,                ┆ Příběhy z Větrné hory           │
│ 1984 ┆ Springer, Michael,            ┆ Co se stalo zítra               │
│ 1984 ┆ Fekete, Ján,                  ┆ Hudba pro vesmířany             │
│ 1985 ┆ Bauman, Milan,                ┆ Labyrint říše rozumu            │
│ 1986 ┆ Moravec, Miroslav,            ┆ Stanice u Moře dešťů            │
│ 1988 ┆ Bauman, Milan,                ┆ Záhady pro zítřek               │
│ 1989 ┆ null                          ┆ SF-Svět, fakta, fantazie        │
│ 1989 ┆ Neff, Ondřej,                 ┆ Čarodějův učeň                  │
│ 1991 ┆ Neff, Ondřej,                 ┆ Šídlo v pytli                   │
│ 1991 ┆ Clarke, Arthur C.             ┆ 2061: Třetí vesmírná odysea     │
│ 1992 ┆ Troska, J. M.                 ┆ Kapitán Nemo                    │
│ 1992 ┆ Troska, J. M.                 ┆ Kapitán Nemo                    │
│ 1992 ┆ Semerád, Václav,              ┆ Kerré, bohyně z hvězd           │
│ 1992 ┆ Troska, J. M.                 ┆ Kapitán Nemo                    │
│ 1992 ┆ Howard, Robert Ervin,         ┆ Zorl                            │
│ 1992 ┆ Talaš, Vlastimír,             ┆ Neuvěřitelná setkání            │
│ 1992 ┆ Troska, J. M.                 ┆ Zápas s nebem                   │
│ 1992 ┆ Troska, J. M.                 ┆ Zápas s nebem                   │
│ 1992 ┆ Troska, J. M.                 ┆ Zápas s nebem                   │
│ 1993 ┆ null                          ┆ Světy science fiction           │
│ 1993 ┆ L'Amour, Louis,               ┆ Drsnou vysočinou                │
│ 1993 ┆ Štefl, Vítězslav,             ┆ Jeden den                       │
│ 1993 ┆ Troska, J. M.                 ┆ Planeta Leon                    │
│ 1994 ┆ Troska, J. M.                 ┆ Záhadný ostrov                  │
│ 1995 ┆ null                          ┆ Anabis                          │
│ 1995 ┆ Lem, Stanisław,               ┆ Summa technologiae              │
│ 2022 ┆ Pospiszyl, Tomáš,             ┆ Rotrekl                         │
└──────┴───────────────────────────────┴─────────────────────────────────┘

In [11]:
df.filter(pl.col("100_a") == "Doubek, Jan").select(pl.col(['rok','100_a','245_a'])).sort(by='rok')

shape: (2, 3)
┌──────┬─────────────┬─────────────────────────────────┐
│ rok  ┆ 100_a       ┆ 245_a                           │
│ ---  ┆ ---         ┆ ---                             │
│ i64  ┆ str         ┆ str                             │
╞══════╪═════════════╪═════════════════════════════════╡
│ 1968 ┆ Doubek, Jan ┆ Co je uvnitř?                   │
│ 1981 ┆ Doubek, Jan ┆ Detektory infračerveného zářen… │
└──────┴─────────────┴─────────────────────────────────┘