In [1]:
import os
import polars as pl
from src.bez_bordelu import bez_bordelu
from src.najdi_rok import najdi_rok
from src.pocet_stran import pocet_stran
pl.Config(tbl_rows=500)

In [3]:
df = pl.read_parquet(
    os.path.join("data","cnb_vyber.parquet")
).with_columns(
    pl.col('300_a').map_elements(pocet_stran, return_dtype=int).alias('stran')
).with_columns(
    pl.col('008').map_elements(najdi_rok, return_dtype=int).alias('rok')
).with_columns(
    pl.col('245_a').map_elements(bez_bordelu, return_dtype=str)
)

In [9]:
pl.read_parquet(os.path.join("data/cnb_sloupce","leader.parquet"))

shape: (1_250_624, 2)
┌──────────────────────────┬────────────────┐
│ leader                   ┆ 001            │
│ ---                      ┆ ---            │
│ str                      ┆ str            │
╞══════════════════════════╪════════════════╡
│      nam a22        4500 ┆ ck8300078      │
│      nam a22        4500 ┆ ck8300080      │
│      nam a22        4500 ┆ ck8300081      │
│      nam a22        4500 ┆ ck8300082      │
│      nam a22        4500 ┆ ck8300083      │
│      nam a22        4500 ┆ ck8300084      │
│      nam a22        4500 ┆ ck8300074      │
│      nam a22        4500 ┆ ck8300086      │
│      nam a22        4500 ┆ ck8300087      │
│      nam a22        4500 ┆ ck8300088      │
│      nam a22        4500 ┆ ck8300089      │
│      nam a22        4500 ┆ ck8300090      │
│      nam a22     2  4500 ┆ ck8300091      │
│      nam a22        4500 ┆ ck8300092      │
│      nam a22        4500 ┆ ck8300093      │
│      nam a22        4500 ┆ ck8300094      │
│      nam a22        4500 ┆ ck8300095      │
│      nam a22        4500 ┆ ck8300096      │
│      nam a22        4500 ┆ ck8300098      │
│      nam a22        4500 ┆ ck8300099      │
│      nam a22        4500 ┆ ck8300100      │
│      nam a22        4500 ┆ ck8300101      │
│      nam a22        4500 ┆ ck8300102      │
│      nam a22        4500 ┆ gk48090496     │
│      nam a22        4500 ┆ ck8300104      │
│      nam a22        4500 ┆ ck8300107      │
│      nam a22        4500 ┆ ck8300108      │
│      nam a22        4500 ┆ ck8300109      │
│      nam a22        4500 ┆ ck8300110      │
│      nam a22        4500 ┆ ck8300111      │
│      nam a22        4500 ┆ ck8300112      │
│      nam a22        4500 ┆ ck8300113      │
│      nam a22        4500 ┆ ck8300114      │
│      nam a22        4500 ┆ ck8300115      │
│      nam a22        4500 ┆ ck8300116      │
│      nam a22        4500 ┆ ck8300117      │
│      nam a22        4500 ┆ ck8300118      │
│      nam a22        4500 ┆ ck8300119      │
│      nam a22        4500 ┆ ck8300120      │
│      nam a22        4500 ┆ ck8300121      │
│      nam a22        4500 ┆ ck8300122      │
│      nam a22        4500 ┆ ck8300123      │
│      nam a22        4500 ┆ ck8300124      │
│      nam a22        4500 ┆ ck8300125      │
│      nam a22        4500 ┆ ck8300126      │
│      nam a22        4500 ┆ ck8300128      │
│      nam a22        4500 ┆ ck8300129      │
│      nam a22        4500 ┆ ck8300130      │
│      nam a22        4500 ┆ ck8300131      │
│      nam a22        4500 ┆ ck8300132      │
│      nam a22        4500 ┆ ck8300133      │
│      nam a22        4500 ┆ ck8300134      │
│      nam a22        4500 ┆ ck8300135      │
│      nam a22        4500 ┆ ck8300136      │
│      nam a22        4500 ┆ ck8300137      │
│      nam a22        4500 ┆ ck8300138      │
│      nam a22        4500 ┆ ck8300140      │
│      nam a22        4500 ┆ ck8300141      │
│      nam a22        4500 ┆ ck8300142      │
│      nam a22        4500 ┆ ck8300143      │
│      nam a22        4500 ┆ ck8300144      │
│      nam a22        4500 ┆ ck8300145      │
│      nam a22        4500 ┆ ck8300148      │
│      nam a22        4500 ┆ ck8300149      │
│      nam a22      i 4500 ┆ ck8300150      │
│      nam a22        4500 ┆ bkn20030000169 │
│      nam a22        4500 ┆ ck8300153      │
│      nam a22        4500 ┆ ck8300154      │
│      nam a22        4500 ┆ ck8300155      │
│      nam a22        4500 ┆ ck8300157      │
│      nam a22        4500 ┆ ck8300158      │
│      nam a22        4500 ┆ ck8300159      │
│      nam a22      i 4500 ┆ ck8300160      │
│      nam a22        4500 ┆ ck8300161      │
│      nam a22        4500 ┆ ck8300163      │
│      nam a22        4500 ┆ ck8300166      │
│      nam a22        4500 ┆ ck8300167      │
│      nam a22        4500 ┆ ck8300169      │
│      nam a22        4500 ┆ ck8300170      │
│      nam a22        4500 ┆ ck8300171      │
│      nam a22        4500 ┆ ck8300172      │
│      nam a22        4500 ┆ ck8300173      │
│      nam a22        4500 ┆ ck8300050      │
│      nam a22        4500 ┆ ck8300175      │
│      nam a22        4500 ┆ ck8300176      │
│      nam a22        4500 ┆ ck8300177      │
│      nam a22        4500 ┆ ck8300179      │
│      nam a22        4500 ┆ ck8300180      │
│      nam a22     2  4500 ┆ ck8300181      │
│      nam a22        4500 ┆ ck8300182      │
│      nam a22        4500 ┆ ck8300183      │
│      nam a22        4500 ┆ ck8300184      │
│      nam a22      a 4500 ┆ ck8300185      │
│      nam a22        4500 ┆ ck8300188      │
│      nam a22        4500 ┆ ck8300189      │
│      nam a22        4500 ┆ ck8300190      │
│      nam a22        4500 ┆ ck8300194      │
│      nam a22        4500 ┆ ck8300196      │
│      nam a22      a 4500 ┆ ck8300197      │
│      nam a22      i 4500 ┆ ck8300198      │
│      nam a22        4500 ┆ ck8300199      │
│      nam a22        4500 ┆ ck8300200      │
│      nam a22        4500 ┆ ck8300201      │
│      nam a22        4500 ┆ ck8300202      │
│      nam a22      a 4500 ┆ cpk19990000222 │
│      nam a22        4500 ┆ ck8300205      │
│      nam a22        4500 ┆ ck8300206      │
│      nam a22        4500 ┆ ck8300207      │
│      nam a22        4500 ┆ ck8300208      │
│      nam a22        4500 ┆ ck8300209      │
│      nam a22        4500 ┆ ck8300210      │
│      nam a22        4500 ┆ ck8300211      │
│      nam a22        4500 ┆ ck8300213      │
│      nam a22        4500 ┆ ck8300215      │
│      nam a22        4500 ┆ ck8300216      │
│      nam a22        4500 ┆ ck8300217      │
│      nam a22     2  4500 ┆ ck8300218      │
│      nam a22        4500 ┆ ck8300219      │
│      nam a22        4500 ┆ ck8300220      │
│      nam a22        4500 ┆ ck8300221      │
│      nam a22        4500 ┆ ck8300222      │
│      nam a22        4500 ┆ ck8300223      │
│      nam a22        4500 ┆ ck8300224      │
│      nam a22        4500 ┆ ck8300225      │
│      nam a22        4500 ┆ ck8300226      │
│      nam a22        4500 ┆ ck8300227      │
│      nam a22        4500 ┆ ck8300228      │
│      nam a22        4500 ┆ ck8300230      │
│      nam a22        4500 ┆ bkn20020000250 │
│      nam a22        4500 ┆ ck8300232      │
│      nam a22        4500 ┆ ck8300233      │
│      nam a22        4500 ┆ ck8300234      │
│      nam a22        4500 ┆ ck8300235      │
│      nam a22        4500 ┆ ck8300236      │
│      nam a22        4500 ┆ ck8300237      │
│      nam a22        4500 ┆ ck8300238      │
│      nam a22        4500 ┆ ck8300239      │
│      cam a22        4500 ┆ ck8300240      │
│      nam a22        4500 ┆ ck8300241      │
│      nam a22        4500 ┆ ck8300242      │
│      nam a22        4500 ┆ ck8300243      │
│      nam a22        4500 ┆ ck8300244      │
│      nam a22        4500 ┆ ck8300245      │
│      nam a22        4500 ┆ ck8300246      │
│      nam a22        4500 ┆ ck8300247      │
│      nam a22        4500 ┆ ck8300248      │
│      nam a22        4500 ┆ ck8300249      │
│      nam a22        4500 ┆ ck8300250      │
│      nam a22        4500 ┆ ck8300251      │
│      nam a22        4500 ┆ ck8300253      │
│      nam a22        4500 ┆ ck8300254      │
│      nam a22        4500 ┆ ck8300255      │
│      nam a22        4500 ┆ ck8300256      │
│      nam a22        4500 ┆ ck8300257      │
│      nam a22        4500 ┆ ck8300259      │
│      nam a22        4500 ┆ ck8300260      │
│      nam a22        4500 ┆ ck8300261      │
│      nam a22        4500 ┆ ck8300263      │
│      nam a22        4500 ┆ ck8300265      │
│      nam a22        4500 ┆ ck8300266      │
│      nam a22        4500 ┆ ck8300267      │
│      nam a22        4500 ┆ ck8300268      │
│      nam a22        4500 ┆ ck8300269      │
│      nam a22        4500 ┆ ck8300270      │
│      nam a22      a 4500 ┆ ck8300272      │
│      nam a22        4500 ┆ ck8300274      │
│      nam a22        4500 ┆ ck8300275      │
│      nam a22        4500 ┆ ck8300276      │
│      nam a22        4500 ┆ ck8300277      │
│      nam a22        4500 ┆ ck8300279      │
│      nam a22        4500 ┆ ck8300280      │
│      nam a22        4500 ┆ ck8300284      │
│      nam a22        4500 ┆ ck8300285      │
│      nam a22        4500 ┆ ck8300286      │
│      nam a22        4500 ┆ ck8300287      │
│      nam a22        4500 ┆ ck8300288      │
│      nam a22        4500 ┆ ck8300290      │
│      nam a22        4500 ┆ ck8300291      │
│      nam a22        4500 ┆ ck8300292      │
│      nam a22        4500 ┆ ck8300293      │
│      nam a22        4500 ┆ ck8300294      │
│      nam a22        4500 ┆ ck8300295      │
│      nam a22        4500 ┆ ck8300296      │
│      nam a22        4500 ┆ ck8300298      │
│      nam a22        4500 ┆ ck8300299      │
│      nam a22      a 4500 ┆ cpk20020000320 │
│      nam a22        4500 ┆ ck8300302      │
│      nam a22        4500 ┆ ck8300304      │
│      nam a22        4500 ┆ ck8300305      │
│      nam a22        4500 ┆ ck8300306      │
│      nam a22        4500 ┆ ck8300307      │
│      nam a22        4500 ┆ ck8300308      │
│      nam a22      i 4500 ┆ srk19960000328 │
│      nam a22        4500 ┆ ck8300310      │
│      nam a22        4500 ┆ ck8300311      │
│      nam a22        4500 ┆ ck8300313      │
│      nam a22        4500 ┆ ck8300314      │
│      nam a22      a 4500 ┆ cpk19950000336 │
│      nam a22        4500 ┆ ck8300319      │
│      nam a22        4500 ┆ ck8300320      │
│      cam a22        4500 ┆ ck8300321      │
│      nam a22        4500 ┆ ck8300322      │
│      nam a22        4500 ┆ ck8300323      │
│      nam a22        4500 ┆ ck8300324      │
│      nam a22        4500 ┆ ck8300325      │
│      nam a22        4500 ┆ ck8300326      │
│      nam a22        4500 ┆ ck8300327      │
│      nam a22      a 4500 ┆ ck8300328      │
│      nam a22        4500 ┆ ck8300329      │
│      nam a22        4500 ┆ ck8300330      │
│      nam a22        4500 ┆ ck8300331      │
│      nam a22        4500 ┆ ck8300332      │
│      nam a22        4500 ┆ ck8300333      │
│      nam a22        4500 ┆ ck8300334      │
│      nam a22        4500 ┆ ck8300335      │
│      nam a22     2  4500 ┆ srk19960000355 │
│      nam a22        4500 ┆ ck8300337      │
│      nam a22        4500 ┆ ck8300338      │
│      nam a22        4500 ┆ ck8300339      │
│      nam a22        4500 ┆ ck8300344      │
│      nam a22      i 4500 ┆ ck8300345      │
│      nam a22      a 4500 ┆ ck8300346      │
│      nam a22        4500 ┆ ck8300347      │
│      nam a22        4500 ┆ ck8300348      │
│      nam a22      a 4500 ┆ ck8300349      │
│      nam a22        4500 ┆ ck8300350      │
│      nam a22        4500 ┆ ck8300351      │
│      nam a22      a 4500 ┆ ck8300352      │
│      nam a22        4500 ┆ ck8300353      │
│      nam a22        4500 ┆ ck8300354      │
│      nam a22        4500 ┆ ck8300355      │
│      nam a22        4500 ┆ ck8300356      │
│      nam a22        4500 ┆ ck8300357      │
│      nam a22        4500 ┆ ck8300358      │
│      nam a22        4500 ┆ ck8300359      │
│      nam a22        4500 ┆ ck8300360      │
│      nam a22      a 4500 ┆ ck8300361      │
│      nam a22        4500 ┆ ck8300362      │
│      nam a22        4500 ┆ ck8300363      │
│      nam a22        4500 ┆ ck8300364      │
│      nam a22        4500 ┆ ck8300365      │
│      nam a22        4500 ┆ ck8300366      │
│      nam a22        4500 ┆ ck8300367      │
│      nam a22        4500 ┆ ck8300368      │
│      nam a22        4500 ┆ ck8300369      │
│      nam a22        4500 ┆ ck8300370      │
│      nam a22        4500 ┆ ck8300371      │
│      nam a22        4500 ┆ ck8300372      │
│      nam a22        4500 ┆ ck8300374      │
│      nam a22        4500 ┆ ck8300375      │
│ …                        ┆ …              │
│      cam a22      i 4500 ┆ cpk20253672935 │
│      cam a22      i 4500 ┆ cpk20253672936 │
│      cam a22      i 4500 ┆ cpk20253672937 │
│      cam a22      i 4500 ┆ cpk20253672938 │
│      cam a22      i 4500 ┆ cpk20253672939 │
│      cam a22      i 4500 ┆ cpk20253672940 │
│      cam a22      a 4500 ┆ cpk20253672941 │
│      cam a22      i 4500 ┆ cpk20253672945 │
│      cam a22      i 4500 ┆ cpk20253672946 │
│      cam a22      i 4500 ┆ cpk20253672947 │
│      cam a22      i 4500 ┆ cpk20253672948 │
│      cam a22      i 4500 ┆ cpk20253672949 │
│      nam a22      ia4500 ┆ nkc20253672978 │
│      cam a22      i 4500 ┆ cpk20253672985 │
│      njm a22      i 4500 ┆ cpz20253672990 │
│      nam a22      i 4500 ┆ nkc20253672995 │
│      nam a22      i 4500 ┆ nkc20253672996 │
│      nam a22     1i 4500 ┆ nkc20253673000 │
│      nam a22      i 4500 ┆ nkc20253673002 │
│      cam a22      i 4500 ┆ nkc20253673005 │
│      nam a22      i 4500 ┆ nkc20253673007 │
│      cam a22      i 4500 ┆ nkc20253673008 │
│      nam a22      i 4500 ┆ nkc20253673019 │
│      nam a22      i 4500 ┆ nkc20253673021 │
│      nam a22      i 4500 ┆ nkc20253673022 │
│      nam a22      i 4500 ┆ nkc20253673023 │
│      njm a22      i 4500 ┆ cpz20253673027 │
│      nam a22      i 4500 ┆ nkc20253673028 │
│      nam a22      i 4500 ┆ nkc20253673029 │
│      nam a22      i 4500 ┆ nkc20253673030 │
│      nam a22      ia4500 ┆ cpk20253673037 │
│      nam a22      ia4500 ┆ cpk20253673040 │
│      nam a22      i 4500 ┆ nkc20253673042 │
│      nam a22      i 4500 ┆ nkc20253673043 │
│      nam a22      i 4500 ┆ nkc20253673044 │
│      nai a22      i 4500 ┆ web20253673049 │
│      nam a22      i 4500 ┆ nkc20253673050 │
│      nam a22      i 4500 ┆ nkc20253673051 │
│      nam a22      i 4500 ┆ nkc20253673053 │
│      nam a22      i 4500 ┆ nkc20253673054 │
│      njm a22      i 4500 ┆ cpz20253673057 │
│      nam a22      i 4500 ┆ nkc20253673058 │
│      nas a22      i 4500 ┆ cps20253673061 │
│      nam a22      i 4500 ┆ nkc20253673063 │
│      nam a22      i 4500 ┆ nkc20253673064 │
│      ncm a22      i 4500 ┆ nkc20253673071 │
│      nam a22      i 4500 ┆ nkc20253673072 │
│      nam a22      i 4500 ┆ nkc20253673073 │
│      nam a22      i 4500 ┆ nkc20253673074 │
│      nam a22      i 4500 ┆ nkc20253673075 │
│      nem a22      i 4500 ┆ nkc20253673076 │
│      njm a22      i 4500 ┆ cpz20253673077 │
│      cam a22      i 4500 ┆ cpk20253673079 │
│      nam a22      i 4500 ┆ nkc20253673080 │
│      nam a22      i 4500 ┆ cpk20253673081 │
│      nam a22      i 4500 ┆ cpk20253673083 │
│      ncm a22      i 4500 ┆ nkc20253673088 │
│      nam a22      i 4500 ┆ nkc20253673089 │
│      nam a22      i 4500 ┆ nkc20253673090 │
│      ncm a22      i 4500 ┆ nkc20253673091 │
│      ncm a22      i 4500 ┆ nkc20253673095 │
│      ncm a22      i 4500 ┆ nkc20253673106 │
│      ncm a22      i 4500 ┆ nkc20253673107 │
│      nam a22      i 4500 ┆ nkc20253673117 │
│      nam a22      aa4500 ┆ cpk20253673138 │
│      nam a22      i 4500 ┆ nkc20253673141 │
│      nam a22      i 4500 ┆ nkc20253673142 │
│      nam a22      i 4500 ┆ nkc20253673146 │
│      nam a22      i 4500 ┆ nkc20253673150 │
│      cas a22      i 4500 ┆ cps20253673151 │
│      njm a22      i 4500 ┆ cpz20253673153 │
│      cam a22      a 4500 ┆ cpk20253673160 │
│      nam a22      ia4500 ┆ nkc20253673171 │
│      cas a22      i 4500 ┆ cps20253673172 │
│      njm a22      i 4500 ┆ cpz20253673173 │
│      ncm a22      i 4500 ┆ nkc20253673179 │
│      ncm a22      i 4500 ┆ nkc20253673181 │
│      nam a22      ia4500 ┆ nkc20253673185 │
│      nam a22      ia4500 ┆ nkc20253673193 │
│      nam a22      i 4500 ┆ nkc20253673197 │
│      nam a22      i 4500 ┆ nkc20253673198 │
│      nam a22      i 4500 ┆ nkc20253673199 │
│      ncm a22      i 4500 ┆ nkc20253673201 │
│      ncm a22      i 4500 ┆ nkc20253673207 │
│      nai a22      i 4500 ┆ web20253673210 │
│      ncm a22      i 4500 ┆ nkc20253673213 │
│      nai a22      i 4500 ┆ web20253673214 │
│      nai a22      i 4500 ┆ web20253673217 │
│      ncm a22      i 4500 ┆ nkc20253673223 │
│      nam a22      ia4500 ┆ nkc20253673224 │
│      ncm a22      i 4500 ┆ nkc20253673235 │
│      nam a22     1a 4500 ┆ gk18050316     │
│      cas a22      i 4500 ┆ cps20253673238 │
│      ncm a22      i 4500 ┆ nkc20253673239 │
│      ncm a22      i 4500 ┆ nkc20253673240 │
│      cas a22      i 4500 ┆ cps20253673242 │
│      cas a22      i 4500 ┆ cps20253673243 │
│      cam a22      aa4500 ┆ cpk20253673245 │
│      cam a22      i 4500 ┆ cpk20253673246 │
│      cam a22      ia4500 ┆ cpk20253673247 │
│      cam a22      i 4500 ┆ cpk20253673249 │
│      cam a22      i 4500 ┆ cpk20253673250 │
│      nam a22      i 4500 ┆ nkc20253673323 │
│      njm a22      i 4500 ┆ cpz20253673334 │
│      nam a22      i 4500 ┆ nkc20253673337 │
│      nas a22      i 4500 ┆ cps20253673340 │
│      nas a22      i 4500 ┆ cps20253673345 │
│      njm a22      i 4500 ┆ cpz20253673357 │
│      ckm a22      i 4500 ┆ cpg20253673359 │
│      ckm a22      i 4500 ┆ cpg20253673360 │
│      nam a22      i 4500 ┆ cpk20253673367 │
│      nam a22      i 4500 ┆ nkc20253673373 │
│      nam a22      i 4500 ┆ nkc20253673374 │
│      nam a22      i 4500 ┆ nkc20253673375 │
│      nam a22      i 4500 ┆ nkc20253673376 │
│      nam a22      i 4500 ┆ cpk20253673390 │
│      njm a22      i 4500 ┆ cpz20253673393 │
│      nam a22      i 4500 ┆ cpk20253673395 │
│      nam a22      i 4500 ┆ cpk20253673400 │
│      ckm a22      i 4500 ┆ cpg20253673402 │
│      nam a22      i 4500 ┆ cpk20253673421 │
│      nam a22      i 4500 ┆ nkc20253673424 │
│      nam a22      i 4500 ┆ nkc20253673425 │
│      njm a22      i 4500 ┆ cpz20253673426 │
│      ncm a22      i 4500 ┆ cph20253673427 │
│      ckm a22      i 4500 ┆ cpg20253673429 │
│      ckm a22      i 4500 ┆ cpg20253673430 │
│      ckm a22      i 4500 ┆ cpg20253673431 │
│      ncm a22      i 4500 ┆ cph20253673432 │
│      nkm a22      i 4500 ┆ cpg20253673441 │
│      nam a22      i 4500 ┆ nkc20253673503 │
│      nam a22      i 4500 ┆ nkc20253673504 │
│      nam a22      i 4500 ┆ nkc20253673505 │
│      nam a22      i 4500 ┆ nkc20253673511 │
│      nam a22      i 4500 ┆ nkc20253673513 │
│      nam a22      i 4500 ┆ nkc20253673514 │
│      nam a22      i 4500 ┆ nkc20253673588 │
│      nam a22      i 4500 ┆ nkc20253673591 │
│      njm a22      i 4500 ┆ cpz20253673592 │
│      nam a22      i 4500 ┆ nkc20253673600 │
│      nam a22      i 4500 ┆ nkc20253673601 │
│      nam a22      ia4500 ┆ nkc20253673602 │
│      nam a22      i 4500 ┆ nkc20253673603 │
│      njm a22      i 4500 ┆ cpz20253673614 │
│      nkm a22      i 4500 ┆ cpg20253673622 │
│      cam a22      aa4500 ┆ cpk20253673625 │
│      cam a22      i 4500 ┆ cpk20253673628 │
│      cam a22      a 4500 ┆ cpk20253673630 │
│      cam a22      a 4500 ┆ cpk20253673631 │
│      nkm a22      i 4500 ┆ cpg20253673633 │
│      nam a22      i 4500 ┆ nkc20253673637 │
│      nam a22      i 4500 ┆ nkc20253673638 │
│      nam a22      i 4500 ┆ nkc20253673639 │
│      nam a22      i 4500 ┆ nkc20253673640 │
│      nam a22      i 4500 ┆ nkc20253673641 │
│      njm a22      i 4500 ┆ cpz20253673642 │
│      nkm a22      i 4500 ┆ cpg20253673650 │
│      cam a22      a 4500 ┆ cpk20253673653 │
│      cam a22      a 4500 ┆ cpk20253673654 │
│      cam a22      a 4500 ┆ cpk20253673656 │
│      cam a22      i 4500 ┆ cpk20253673657 │
│      cam a22      a 4500 ┆ cpk20253673658 │
│      cam a22      i 4500 ┆ cpk20253673660 │
│      cam a22      a 4500 ┆ cpk20253673664 │
│      nkm a22      i 4500 ┆ cpg20253673666 │
│      njm a22      i 4500 ┆ cpz20253673667 │
│      cam a22      a 4500 ┆ cpk20253673670 │
│      cam a22      a 4500 ┆ cpk20253673671 │
│      cam a22      a 4500 ┆ cpk20253673672 │
│      cam a22      a 4500 ┆ cpk20253673675 │
│      cam a22      a 4500 ┆ cpk20253673678 │
│      cam a22      a 4500 ┆ cpk20253673679 │
│      nam a22      ia4500 ┆ nkc20253673777 │
│      cam a22      aa4500 ┆ cpk20253673780 │
│      cam a22      a 4500 ┆ cpk20253673782 │
│      nam a22      i 4500 ┆ nkc20253673790 │
│      nkm a22      i 4500 ┆ cpg20253673797 │
│      nkm a22      i 4500 ┆ cpg20253673805 │

In [4]:
df.filter(pl.col("rok") == 2024).sample().select(pl.col("008")).to_series().to_list()

['241219s2024    xr     g      000 p cze']

In [ ]:
df.filter(pl.col("rok") == 2024).sample().select(pl.col("008")).to_series().to_list()

In [4]:
df.filter(pl.col("rok") == 2024).sample()

shape: (1, 64)
┌─────────────────┬─────────────────┬───────────┬─────────────────┬───┬────────────────┬────────────────┬───────┬──────┐
│ 008             ┆ 020_a           ┆ 020_c     ┆ 020_q           ┆ … ┆ leader         ┆ 001            ┆ stran ┆ rok  │
│ ---             ┆ ---             ┆ ---       ┆ ---             ┆   ┆ ---            ┆ ---            ┆ ---   ┆ ---  │
│ str             ┆ list[str]       ┆ list[str] ┆ list[str]       ┆   ┆ str            ┆ str            ┆ i64   ┆ i64  │
╞═════════════════╪═════════════════╪═══════════╪═════════════════╪═══╪════════════════╪════════════════╪═══════╪══════╡
│ 240815s2024     ┆ ["978-80-7332-5 ┆ null      ┆ ["(brožováno)"] ┆ … ┆ nam a22      i ┆ nkc20243626816 ┆ 262   ┆ 2024 │
│ xr     g        ┆ 52-7"]          ┆           ┆                 ┆   ┆ 4500           ┆                ┆       ┆      │
│ 0…              ┆                 ┆           ┆                 ┆   ┆                ┆                ┆       ┆      │
└─────────────────┴─────────────────┴───────────┴─────────────────┴───┴────────────────┴────────────────┴───────┴──────┘

In [7]:
df.select(pl.col("020_a")).sample(10)

shape: (10, 1)
┌───────────────────────┐
│ 020_a                 │
│ ---                   │
│ list[str]             │
╞═══════════════════════╡
│ null                  │
│ ["978-80-7435-613-1"] │
│ ["978-80-7306-436-5"] │
│ null                  │
│ null                  │
│ ["80-901892-0-2"]     │
│ null                  │
│ null                  │
│ null                  │
│ null                  │
└───────────────────────┘

In [ ]:
df.filter(pl.col("245_a") == "Po")

In [9]:
df.explode("020_a").filter(pl.col("020_a") == "987-80-00-02756-2")

shape: (0, 64)
┌─────┬───────┬───────────┬───────────┬───┬────────┬─────┬───────┬─────┐
│ 008 ┆ 020_a ┆ 020_c     ┆ 020_q     ┆ … ┆ leader ┆ 001 ┆ stran ┆ rok │
│ --- ┆ ---   ┆ ---       ┆ ---       ┆   ┆ ---    ┆ --- ┆ ---   ┆ --- │
│ str ┆ str   ┆ list[str] ┆ list[str] ┆   ┆ str    ┆ str ┆ i64   ┆ i64 │
╞═════╪═══════╪═══════════╪═══════════╪═══╪════════╪═════╪═══════╪═════╡
└─────┴───────┴───────────┴───────────┴───┴────────┴─────┴───────┴─────┘