In [1]:
import os
import datetime
import warnings
import json
import polars as pl
import pandas as pd
import altair as alt

from src.najdi_rok import najdi_rok
from src.pocet_stran import pocet_stran
from src.bez_bordelu import bez_bordelu
from src.alt_friendly import alt_friendly
from src.hezke_jmeno import hezke_jmeno
from src.kristi_promin import kristi_promin
from src.zjisti_vazbu import zjisti_vazbu
from src.me_to_neurazi import me_to_neurazi

pl.Config(tbl_rows=100)
alt.data_transformers.disable_max_rows()
alt.themes.register('irozhlas', kristi_promin)
alt.themes.enable('irozhlas')
warnings.filterwarnings('ignore')

In [2]:
with open(os.path.join('src','kredity.json'), 'r', encoding='utf-8') as kredity:
    kredity = json.loads(kredity.read())

In [3]:
with open(os.path.join('barvy','barvy.json'), 'r', encoding='utf-8') as palety:
    palety = json.loads(palety.read())

In [4]:
df = pl.read_parquet('data/cnb_vyber.parquet')

In [5]:
df = df.with_columns(pl.col('008').map_elements(najdi_rok, return_dtype=int).alias('rok'))

In [6]:
petdvanula = pl.read_parquet("data/cnb_sloupce/520.parquet")
df = df.join(petdvanula, on='001', how='left')

In [7]:
pl.read_parquet("data/cnb_sloupce/041.parquet")

shape: (384_535, 13)
┌──────────┬──────────────────┬───────────┬───────────────────────────┬───┬───────────┬───────┬───────┬────────────────┐
│ 041_ind1 ┆ 041_a            ┆ 041_h     ┆ 041_b                     ┆ … ┆ 041_j     ┆ 041_n ┆ 041_m ┆ 001            │
│ ---      ┆ ---              ┆ ---       ┆ ---                       ┆   ┆ ---       ┆ ---   ┆ ---   ┆ ---            │
│ str      ┆ list[str]        ┆ list[str] ┆ list[str]                 ┆   ┆ list[str] ┆ str   ┆ str   ┆ str            │
╞══════════╪══════════════════╪═══════════╪═══════════════════════════╪═══╪═══════════╪═══════╪═══════╪════════════════╡
│ 1        ┆ ["eng"]          ┆ ["und"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300094      │
│ 1        ┆ ["cze"]          ┆ ["rus"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300101      │
│ 1        ┆ ["cze"]          ┆ ["slo"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300109      │
│ 0        ┆ ["cze", "rus"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300112      │
│ 1        ┆ ["cze"]          ┆ ["slo"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300119      │
│ 1        ┆ ["pol"]          ┆ ["cze"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300122      │
│ 1        ┆ ["cze"]          ┆ ["slo"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300123      │
│ 1        ┆ ["pol", "rus"]   ┆ ["cze"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300124      │
│ 0        ┆ ["cze", "pol"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300134      │
│ 1        ┆ ["cze"]          ┆ ["slo"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300150      │
│ 0        ┆ ["cze"]          ┆ null      ┆ ["eng", "rus"]            ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300158      │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300160      │
│ 1        ┆ ["cze"]          ┆ ["rus"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300050      │
│ 1        ┆ ["cze"]          ┆ ["slo"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300175      │
│ 0        ┆ ["eng"]          ┆ null      ┆ ["rus", "cze"]            ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300183      │
│ 1        ┆ ["cze"]          ┆ ["rus"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300184      │
│ 1        ┆ ["cze"]          ┆ null      ┆ ["ger", "rus"]            ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300185      │
│ 0        ┆ ["spa", "cze"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpk19990000222 │
│ 1        ┆ ["eng"]          ┆ ["cze"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300213      │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300215      │
│ 0        ┆ ["eng", "cze"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ bkn20020000250 │
│ 1        ┆ ["slo"]          ┆ ["cze"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300238      │
│ 0        ┆ ["slo", "ger"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300243      │
│ 0        ┆ ["cze", "slo"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300245      │
│ 0        ┆ ["cze"]          ┆ null      ┆ ["eng", "rus"]            ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300265      │
│ 1        ┆ ["cze"]          ┆ ["slo"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300268      │
│ 1        ┆ ["cze"]          ┆ ["slo"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300277      │
│ 0        ┆ ["cze"]          ┆ null      ┆ ["eng", "ger", "rus"]     ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300294      │
│ 1        ┆ ["cze", "eng", … ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300307      │
│          ┆ "rus"]           ┆           ┆                           ┆   ┆           ┆       ┆       ┆                │
│ 0        ┆ ["cze"]          ┆ null      ┆ ["eng", "rus"]            ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300308      │
│ 0        ┆ ["cze"]          ┆ null      ┆ ["eng", "fre", … "spa"]   ┆ … ┆ null      ┆ null  ┆ null  ┆ srk19960000328 │
│ 0        ┆ ["cze"]          ┆ null      ┆ ["eng", "fre", … "rus"]   ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300314      │
│ 1        ┆ ["cze"]          ┆ null      ┆ ["rus", "ger", … "fre"]   ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300320      │
│ 0        ┆ ["cze"]          ┆ null      ┆ ["eng", "ger", "rus"]     ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300321      │
│ 1        ┆ ["eng", "cze"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300327      │
│ 1        ┆ ["eng", "cze"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300328      │
│ 1        ┆ ["cze", "eng",   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300329      │
│          ┆ "fre"]           ┆           ┆                           ┆   ┆           ┆       ┆       ┆                │
│ 1        ┆ ["cze", "vie"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300330      │
│ 0        ┆ ["ger", "cze"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300333      │
│ 0        ┆ ["cze", "dut"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300334      │
│ 0        ┆ ["ger", "cze"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300335      │
│ 0        ┆ ["fre", "cze"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ srk19960000355 │
│ 0        ┆ ["fre", "cze"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300337      │
│ 0        ┆ ["rus", "cze"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300338      │
│ 0        ┆ ["cze", "rus"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300339      │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300344      │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300345      │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300346      │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300347      │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ ck8300348      │
│ …        ┆ …                ┆ …         ┆ …                         ┆ … ┆ …         ┆ …     ┆ …     ┆ …              │
│ 0        ┆ ["cze", "ger"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpg20253673359 │
│ 0        ┆ ["cze", "ger"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpg20253673360 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673375 │
│ 0        ┆ null             ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpz20253673393 │
│ 0        ┆ ["cze", "ger"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpg20253673402 │
│ 1        ┆ ["cze"]          ┆ ["fre"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673425 │
│ 0        ┆ null             ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpz20253673426 │
│ 0        ┆ ["cze", "ger"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpg20253673429 │
│ 0        ┆ ["cze", "ger"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpg20253673430 │
│ 0        ┆ ["cze", "ger"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpg20253673431 │
│ 0        ┆ ["eng", "fre",   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpg20253673441 │
│          ┆ "spa"]           ┆           ┆                           ┆   ┆           ┆       ┆       ┆                │
│ 1        ┆ ["cze"]          ┆ ["ger"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673504 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673505 │
│ 1        ┆ ["cze"]          ┆ ["ger"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673511 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673513 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673514 │
│ 1        ┆ ["cze"]          ┆ ["jpn"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673588 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673591 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673600 │
│ 1        ┆ ["cze"]          ┆ ["jpn"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673602 │
│ 1        ┆ ["cze"]          ┆ ["ger"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673603 │
│ 0        ┆ ["eng", "fre"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpg20253673622 │
│ 0        ┆ ["ger", "fre"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpk20253673625 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673637 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673638 │
│ 1        ┆ ["cze"]          ┆ ["por"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673640 │
│ 0        ┆ null             ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpz20253673667 │
│ 1        ┆ ["cze"]          ┆ ["rus"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpk20253673671 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpk20253673672 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673777 │
│ 0        ┆ ["cze", "eng"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpk20253673782 │
│ 1        ┆ ["cze"]          ┆ ["fre"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673790 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673844 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673845 │
│ 1        ┆ ["cze"]          ┆ ["jpn"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673846 │
│ 0        ┆ ["cze", "slo"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpg20253673848 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673952 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673953 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253673954 │
│ 1        ┆ ["cze"]          ┆ ["rus"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpk20253673970 │
│ 0        ┆ null             ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpz20253674003 │
│ 0        ┆ ["cze", "ger"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpg20253674006 │
│ 0        ┆ ["cze", "slo"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpg20253674009 │
│ 0        ┆ ["cze"]          ┆ null      ┆ ["eng", "fre", … "rus"]   ┆ … ┆ null      ┆ null  ┆ null  ┆ cpk20253674010 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253674014 │
│ 1        ┆ ["cze"]          ┆ ["eng"]   ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ nkc20253674015 │
│ 0        ┆ null             ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpz20253674034 │
│ 0        ┆ ["cze", "ger"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpg20253674036 │
│ 0        ┆ ["cze", "ger"]   ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpg20253674038 │
│ 0        ┆ null             ┆ null      ┆ null                      ┆ … ┆ null      ┆ null  ┆ null  ┆ cpz20253674047 │
└──────────┴──────────────────┴───────────┴───────────────────────────┴───┴───────────┴───────┴───────┴────────────────┘

In [8]:
df = df.join(pl.read_parquet("data/cnb_sloupce/041.parquet"), on="001", how="left")

In [9]:
df = df.explode("041_h").unique(subset=["rok","100_a","245_a","041_h"],keep="first")

In [10]:
df = df.with_columns(
    pl.when(
        ((pl.col('041_h').is_null()) | (pl.col('041_h') == 'cze'))
    ).then(
        pl.lit('původní česká')).otherwise(
            pl.lit("překladová")
    ).alias("preklad"))

In [11]:
tematicke_sloupce = ['072_x','245_a','245_c','245_p','246_a','500_a','520_a','520_b','521_a','648_a','650_a','650_x','650_z','650_y','651_a','653_a','655_a','964_a']

In [12]:
df = df.select(pl.col(['rok','preklad'] + tematicke_sloupce)).with_columns(pl.col(tematicke_sloupce).cast(pl.List(pl.String)).list.join(" "))
df = df.with_columns(pl.col(tematicke_sloupce).fill_null(' ')).with_columns(pl.concat_str([pl.col(t) for t in tematicke_sloupce], separator=" ").alias("keywords"))

In [13]:
def tema(label, keywords):
    return df.filter(pl.col('keywords').str.contains(keywords)).with_columns(téma = pl.lit(label)).with_columns(
               pl.col("rok").map_elements(
                   lambda x: datetime.date(year=x, month=1, day=1), 
                   return_dtype=pl.Date
               ).cast(pl.Datetime)
           )

In [14]:
warnings.filterwarnings("ignore")

In [15]:
def hledej_tema(label, keywords):
    return df.filter(pl.col('rok') > 1945).filter(pl.col('keywords').str.contains(keywords)).with_columns(téma = pl.lit(label)).with_columns(
               pl.col("rok").map_elements(
                   lambda x: datetime.date(year=x, month=1, day=1), 
                   return_dtype=pl.Date
               ).cast(pl.Datetime)
           )

In [16]:
def hledej_tema(label, keywords):
        return df.filter(pl.col('keywords').str.contains(keywords)).with_columns(téma = pl.lit(label))

In [17]:
predpo = df.filter(
    pl.col("rok").is_between(1987,1993)
).with_columns(
    pl.col("keywords").map_elements(lambda x: x.split(" "))
).explode("keywords")

In [18]:
predpo.filter(
    pl.col("rok").is_between(1987,1988)
).group_by('keywords').len().join(
    predpo.filter(
        pl.col("rok").is_between(1990,1992)
    ).group_by('keywords').len(), on='keywords', how='right'
).with_columns((pl.col('len_right') / pl.col('len')).alias('narust')).filter(pl.col('len_right') > 20).filter(pl.col('narust').is_null()).sort(by='len_right',descending=True).head(100)

shape: (100, 4)
┌──────┬────────────────┬───────────┬────────┐
│ len  ┆ keywords       ┆ len_right ┆ narust │
│ ---  ┆ ---            ┆ ---       ┆ ---    │
│ u32  ┆ str            ┆ u32       ┆ f64    │
╞══════╪════════════════╪═══════════╪════════╡
│ null ┆ sčítání        ┆ 3284      ┆ null   │
│ null ┆ bytů           ┆ 1252      ┆ null   │
│ null ┆ Sčítání        ┆ 696       ┆ null   │
│ null ┆ 1991.          ┆ 665       ┆ null   │
│ null ┆ domy,          ┆ 467       ┆ null   │
│ null ┆ Obyvatelstvo,  ┆ 466       ┆ null   │
│ null ┆ domácnosti.    ┆ 465       ┆ null   │
│ null ┆ střed.         ┆ 283       ┆ null   │
│ null ┆ ČSFR           ┆ 191       ┆ null   │
│ null ┆ demografická   ┆ 184       ┆ null   │
│ null ┆ obcí,          ┆ 99        ┆ null   │
│ null ┆ jednotky.      ┆ 94        ┆ null   │
│ null ┆ měst,          ┆ 93        ┆ null   │
│ null ┆ Souhrnné       ┆ 92        ┆ null   │
│ null ┆ 1990-1991      ┆ 84        ┆ null   │
│ null ┆ privatizace    ┆ 80        ┆ null   │
│ null ┆ 1991-2000      ┆ 72        ┆ null   │
│ null ┆ daň            ┆ 69        ┆ null   │
│ null ┆ alternativní   ┆ 60        ┆ null   │
│ null ┆ autobiografie  ┆ 59        ┆ null   │
│ null ┆ Norton         ┆ 57        ┆ null   │
│ null ┆ Patricia       ┆ 57        ┆ null   │
│ null ┆ Vandenbergová  ┆ 54        ┆ null   │
│ null ┆ magazíny       ┆ 54        ┆ null   │
│ null ┆ (hledisko)     ┆ 51        ┆ null   │
│ null ┆ Palackého,     ┆ 50        ┆ null   │
│ null ┆ FoxPro         ┆ 50        ┆ null   │
│ null ┆ Quattro        ┆ 47        ┆ null   │
│ null ┆ Garrigue       ┆ 47        ┆ null   │
│ null ┆ (semináře)     ┆ 47        ┆ null   │
│ null ┆ Daň            ┆ 46        ┆ null   │
│ null ┆ Západočeská    ┆ 45        ┆ null   │
│ null ┆ 0              ┆ 44        ┆ null   │
│ null ┆ Ježíš          ┆ 44        ┆ null   │
│ null ┆ židovské       ┆ 44        ┆ null   │
│ null ┆ 1991-1992      ┆ 43        ┆ null   │
│ null ┆ '90            ┆ 42        ┆ null   │
│ null ┆ Poprvé         ┆ 42        ┆ null   │
│ null ┆ reforma        ┆ 42        ┆ null   │
│ null ┆ 5.0            ┆ 40        ┆ null   │
│ null ┆ SRN            ┆ 40        ┆ null   │
│ null ┆ republika.     ┆ 40        ┆ null   │
│ null ┆ 1990-1992      ┆ 39        ┆ null   │
│ null ┆ Masaryk,       ┆ 39        ┆ null   │
│ null ┆ databázový     ┆ 38        ┆ null   │
│ null ┆ erotické       ┆ 38        ┆ null   │
│ null ┆ boží           ┆ 38        ┆ null   │
│ null ┆ podnikatelé    ┆ 38        ┆ null   │
│ null ┆ Grey           ┆ 37        ┆ null   │
│ null ┆ Novell         ┆ 37        ┆ null   │
│ null ┆ [Přel.         ┆ 37        ┆ null   │
│ null ┆ Ježíše         ┆ 36        ┆ null   │
│ null ┆ Okultismus     ┆ 36        ┆ null   │
│ null ┆ ES             ┆ 36        ┆ null   │
│ null ┆ podnikatele    ┆ 36        ┆ null   │
│ null ┆ řeholní        ┆ 36        ┆ null   │
│ null ┆ NetWare        ┆ 35        ┆ null   │
│ null ┆ Zane           ┆ 35        ┆ null   │
│ null ┆ Federativní    ┆ 35        ┆ null   │
│ null ┆ Škvorecký      ┆ 35        ┆ null   │
│ null ┆ 1948-1989      ┆ 35        ┆ null   │
│ null ┆ 90.,           ┆ 34        ┆ null   │
│ null ┆ Ezoterismus.   ┆ 34        ┆ null   │
│ null ┆ přidané        ┆ 34        ┆ null   │
│ null ┆ sex            ┆ 33        ┆ null   │
│ null ┆ Kancelářské    ┆ 33        ┆ null   │
│ null ┆ [?]            ┆ 33        ┆ null   │
│ null ┆ daňová         ┆ 32        ┆ null   │
│ null ┆ SPEV           ┆ 32        ┆ null   │
│ null ┆ Panny          ┆ 32        ┆ null   │
│ null ┆ skauting       ┆ 31        ┆ null   │
│ null ┆ 1989-1990      ┆ 31        ┆ null   │
│ null ┆ Windows        ┆ 30        ┆ null   │
│ null ┆ 3.0            ┆ 30        ┆ null   │
│ null ┆ Srpen          ┆ 30        ┆ null   │
│ null ┆ podnikatelské  ┆ 30        ┆ null   │
│ null ┆ Dobrá,         ┆ 29        ┆ null   │
│ null ┆ AutoCAD        ┆ 29        ┆ null   │
│ null ┆ 1989-1991      ┆ 29        ┆ null   │
│ null ┆ Daně           ┆ 29        ┆ null   │
│ null ┆ českoslovenští ┆ 28        ┆ null   │
│ null ┆ letectvo       ┆ 28        ┆ null   │
│ null ┆ (konference)   ┆ 28        ┆ null   │
│ null ┆ bahá'í         ┆ 28        ┆ null   │
│ null ┆ horory         ┆ 28        ┆ null   │
│ null ┆ Sixty-Eight    ┆ 28        ┆ null   │
│ null ┆ Hutnický       ┆ 28        ┆ null   │
│ null ┆ Boží           ┆ 28        ┆ null   │
│ null ┆ 1992-1993      ┆ 28        ┆ null   │
│ null ┆ Masarykovy     ┆ 27        ┆ null   │
│ null ┆ (1968          ┆ 27        ┆ null   │
│ null ┆ obratu         ┆ 27        ┆ null   │
│ null ┆ rakouské       ┆ 26        ┆ null   │
│ null ┆ Vrňáková       ┆ 26        ┆ null   │
│ null ┆ institut       ┆ 26        ┆ null   │
│ null ┆ akciové        ┆ 26        ┆ null   │
│ null ┆ mystika        ┆ 26        ┆ null   │
│ null ┆ Publishers     ┆ 26        ┆ null   │
│ null ┆ zjevení        ┆ 25        ┆ null   │
│ null ┆ Commander      ┆ 25        ┆ null   │
└──────┴────────────────┴───────────┴────────┘

In [19]:
hledej_tema("povinnosti","povin")

shape: (1_236, 22)
┌──────┬───────────────┬───────────────┬───────────────┬───┬───────────────┬───────────────┬──────────────┬────────────┐
│ rok  ┆ preklad       ┆ 072_x         ┆ 245_a         ┆ … ┆ 655_a         ┆ 964_a         ┆ keywords     ┆ téma       │
│ ---  ┆ ---           ┆ ---           ┆ ---           ┆   ┆ ---           ┆ ---           ┆ ---          ┆ ---        │
│ i64  ┆ str           ┆ str           ┆ str           ┆   ┆ str           ┆ str           ┆ str          ┆ str        │
╞══════╪═══════════════╪═══════════════╪═══════════════╪═══╪═══════════════╪═══════════════╪══════════════╪════════════╡
│ 1950 ┆ původní česká ┆               ┆ Lisař Kubát : ┆ … ┆               ┆ Budování      ┆ Lisař Kubát  ┆ povinnosti │
│      ┆               ┆               ┆               ┆   ┆               ┆ socialismu -  ┆ : Jiří Beneš ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆ rodina -…     ┆ …            ┆            │
│ 1951 ┆ překladová    ┆               ┆ Borjovi noví  ┆ … ┆               ┆ Škola         ┆ Borjovi noví ┆ povinnosti │
│      ┆               ┆               ┆ přátelé /     ┆   ┆               ┆ mateřská      ┆ přátelé / I. ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆ sovětská -    ┆ Gr…          ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆ vypr…         ┆              ┆            │
│ 1973 ┆ původní česká ┆               ┆ Vyhláška č.   ┆ … ┆               ┆ Provoz        ┆ Vyhláška č.  ┆ povinnosti │
│      ┆               ┆               ┆ 80 z          ┆   ┆               ┆ silniční -    ┆ 80 z         ┆            │
│      ┆               ┆               ┆ 20.10.1966 ;  ┆   ┆               ┆ pravidla Dop… ┆ 20.10.1966 … ┆            │
│ 2022 ┆ překladová    ┆ Americká      ┆ Polibek bez   ┆ … ┆ americké      ┆               ┆ Americká     ┆ povinnosti │
│      ┆               ┆ próza         ┆ duše /        ┆   ┆ romány        ┆               ┆ próza        ┆            │
│      ┆               ┆ Literatura    ┆               ┆   ┆ fantasy       ┆               ┆ Literatura   ┆            │
│      ┆               ┆ pro …         ┆               ┆   ┆ romány…       ┆               ┆ pro …        ┆            │
│ 2021 ┆ překladová    ┆ Německá       ┆ Kroniky       ┆ … ┆ německé       ┆               ┆ Německá      ┆ povinnosti │
│      ┆               ┆ próza,        ┆ prachu /      ┆   ┆ romány        ┆               ┆ próza,       ┆            │
│      ┆               ┆ německy psaná ┆               ┆   ┆ literatura    ┆               ┆ německy      ┆            │
│      ┆               ┆ L…            ┆               ┆   ┆ youn…         ┆               ┆ psaná L…     ┆            │
│ 1951 ┆ překladová    ┆               ┆ Kačátko :     ┆ … ┆               ┆ Hry maňáskové ┆ Kačátko : N. ┆ povinnosti │
│      ┆               ┆               ┆               ┆   ┆               ┆               ┆ Gernětová    ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆               ┆ aT. G…       ┆            │
│ 1942 ┆ překladová    ┆               ┆ Účetnictví v  ┆ … ┆               ┆               ┆ Účetnictví v ┆ povinnosti │
│      ┆               ┆               ┆ maloobchodě   ┆   ┆               ┆               ┆ maloobchodě  ┆            │
│      ┆               ┆               ┆ dle p…        ┆   ┆               ┆               ┆ dle…         ┆            │
│ 1938 ┆ původní česká ┆ Vojenství.    ┆ Zprošťování   ┆ … ┆ předpisy      ┆               ┆ Vojenství.   ┆ povinnosti │
│      ┆               ┆ Obrana země.  ┆ od činné      ┆   ┆               ┆               ┆ Obrana země. ┆            │
│      ┆               ┆ Ozbroj…       ┆ vojenské …    ┆   ┆               ┆               ┆ Ozbroj…      ┆            │
│ 2022 ┆ překladová    ┆ Německá       ┆ Někdo zůstává ┆ … ┆ německé       ┆               ┆ Německá      ┆ povinnosti │
│      ┆               ┆ próza,        ┆ /             ┆   ┆ romány        ┆               ┆ próza,       ┆            │
│      ┆               ┆ německy psaná ┆               ┆   ┆ milostné      ┆               ┆ německy      ┆            │
│      ┆               ┆               ┆               ┆   ┆ romány…       ┆               ┆ psaná N…     ┆            │
│ 1973 ┆ původní česká ┆               ┆ Státní        ┆ … ┆               ┆ Země          ┆ Státní       ┆ povinnosti │
│      ┆               ┆               ┆ zřízení       ┆   ┆               ┆ socialistické ┆ zřízení      ┆            │
│      ┆               ┆               ┆ evropských    ┆   ┆               ┆ evropské - …  ┆ evropských   ┆            │
│      ┆               ┆               ┆ soci…         ┆   ┆               ┆               ┆ so…          ┆            │
│ 2021 ┆ původní česká ┆ Česká próza   ┆ Karlíček a    ┆ … ┆ české příběhy ┆               ┆ Česká próza  ┆ povinnosti │
│      ┆               ┆ Literatura    ┆ vosy :        ┆   ┆ publikace pro ┆               ┆ Literatura   ┆            │
│      ┆               ┆ pro dět…      ┆               ┆   ┆ dě…           ┆               ┆ pro dět…     ┆            │
│ 1953 ┆ původní česká ┆ Česká próza   ┆ Bronzová      ┆ … ┆ české romány  ┆               ┆ Česká próza  ┆ povinnosti │
│      ┆               ┆ Biografie     ┆ spirála /     ┆   ┆ biografické   ┆               ┆ Biografie    ┆            │
│      ┆               ┆               ┆               ┆   ┆ román…        ┆               ┆ Bronzová…    ┆            │
│ 1942 ┆ původní česká ┆               ┆ Anežčina      ┆ … ┆               ┆               ┆ Anežčina     ┆ povinnosti │
│      ┆               ┆               ┆ povinnost :   ┆   ┆               ┆               ┆ povinnost :  ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆               ┆ Eva Mar…     ┆            │
│ 1984 ┆ původní česká ┆               ┆ Práva, nároky ┆ … ┆ příručky      ┆ Osoby se      ┆ Práva,       ┆ povinnosti │
│      ┆               ┆               ┆ a povinnosti  ┆   ┆               ┆ schopností    ┆ nároky a     ┆            │
│      ┆               ┆               ┆ obč…          ┆   ┆               ┆ pracovní z…   ┆ povinnosti   ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆               ┆ o…           ┆            │
│ null ┆ původní česká ┆               ┆ V zájmu       ┆ … ┆               ┆               ┆ V zájmu      ┆ povinnosti │
│      ┆               ┆               ┆ povinnosti :  ┆   ┆               ┆               ┆ povinnosti : ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆               ┆ Napsal …     ┆            │
│ 1900 ┆ původní česká ┆ Globální      ┆ O povinnosti  ┆ … ┆ přednášky     ┆               ┆ Globální     ┆ povinnosti │
│      ┆               ┆ společnosti.  ┆ české ženy /  ┆   ┆               ┆               ┆ společnosti. ┆            │
│      ┆               ┆ Sociální…     ┆               ┆   ┆               ┆               ┆ Sociální…    ┆            │
│ 1970 ┆ původní česká ┆               ┆ Úkoly a       ┆ … ┆               ┆ CO            ┆ Úkoly a      ┆ povinnosti │
│      ┆               ┆               ┆ povinnosti    ┆   ┆               ┆ -zaměstnání   ┆ povinnosti   ┆            │
│      ┆               ┆               ┆ obyvatelstv…  ┆   ┆               ┆ praktická -   ┆ obyvatels…   ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆ náv…          ┆              ┆            │
│ 1975 ┆ původní česká ┆               ┆ O úkolech     ┆ … ┆               ┆ ROH - orgány  ┆ O úkolech    ┆ povinnosti │
│      ┆               ┆               ┆ odborových    ┆   ┆               ┆ - práva a     ┆ odborových   ┆            │
│      ┆               ┆               ┆ orgánů př…    ┆   ┆               ┆ povinno…      ┆ orgánů …     ┆            │
│ 1965 ┆ původní česká ┆               ┆ Líbánky s     ┆ … ┆               ┆ Vojáci čs. -  ┆ Líbánky s    ┆ povinnosti │
│      ┆               ┆               ┆ vojnou /      ┆   ┆               ┆ služba        ┆ vojnou /     ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆ základní -…   ┆ Jiří Jane…   ┆            │
│ 1909 ┆ původní česká ┆ Volby,        ┆ O povinnosti  ┆ … ┆ studie        ┆               ┆ Volby,       ┆ povinnosti │
│      ┆               ┆ volební       ┆ volební :     ┆   ┆               ┆               ┆ volební      ┆            │
│      ┆               ┆ kampaně,      ┆               ┆   ┆               ┆               ┆ kampaně,     ┆            │
│      ┆               ┆ refere…       ┆               ┆   ┆               ┆               ┆ refere…      ┆            │
│ 1998 ┆ překladová    ┆ Vojenství.    ┆ Mezi          ┆ … ┆ válečné       ┆               ┆ Vojenství.   ┆ povinnosti │
│      ┆               ┆ Obrana země.  ┆ povinností a  ┆   ┆ deníky        ┆               ┆ Obrana země. ┆            │
│      ┆               ┆ Ozbroj…       ┆ pochybnostmi… ┆   ┆               ┆               ┆ Ozbroj…      ┆            │
│ 1965 ┆ původní česká ┆ Ústavní       ┆ Ústavní právo ┆ … ┆ učebnice      ┆               ┆ Ústavní      ┆ povinnosti │
│      ┆               ┆ právo.        ┆ ČSSR :        ┆   ┆ vysokých škol ┆               ┆ právo.       ┆            │
│      ┆               ┆ Správní právo ┆               ┆   ┆               ┆               ┆ Správní      ┆            │
│      ┆               ┆ U…            ┆               ┆   ┆               ┆               ┆ právo U…     ┆            │
│ 1964 ┆ původní česká ┆ Učební        ┆ Učební osnovy ┆ … ┆ příručky      ┆               ┆ Učební       ┆ povinnosti │
│      ┆               ┆ osnovy.       ┆ střední školy ┆   ┆               ┆               ┆ osnovy.      ┆            │
│      ┆               ┆ Vyučovací     ┆ pr…           ┆   ┆               ┆               ┆ Vyučovací    ┆            │
│      ┆               ┆ předm…        ┆               ┆   ┆               ┆               ┆ předm…       ┆            │
│ 1936 ┆ původní česká ┆               ┆ Tabulky k     ┆ … ┆               ┆               ┆ Tabulky k    ┆ povinnosti │
│      ┆               ┆               ┆ použití při   ┆   ┆               ┆               ┆ použití při  ┆            │
│      ┆               ┆               ┆ placení …     ┆   ┆               ┆               ┆ placen…      ┆            │
│ 1978 ┆ překladová    ┆               ┆ Ústava Polské ┆ … ┆               ┆ Ústava PLR -  ┆ Ústava       ┆ povinnosti │
│      ┆               ┆               ┆ lidové        ┆   ┆               ┆ text a        ┆ Polské       ┆            │
│      ┆               ┆               ┆ republiky…    ┆   ┆               ┆ výklady       ┆ lidové       ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆               ┆ republi…     ┆            │
│ 2025 ┆ původní česká ┆ Česká próza   ┆ Zkáza ráje /  ┆ … ┆ české romány  ┆               ┆ Česká próza  ┆ povinnosti │
│      ┆               ┆               ┆               ┆   ┆ vědecko-fanta ┆               ┆ Zkáza ráje / ┆            │
│      ┆               ┆               ┆               ┆   ┆ stic…         ┆               ┆ Zdeně…       ┆            │
│ 1951 ┆ překladová    ┆               ┆ Vyrábíme      ┆ … ┆               ┆ Soutěžení     ┆ Vyrábíme     ┆ povinnosti │
│      ┆               ┆               ┆ látky         ┆   ┆               ┆ socialistické ┆ látky        ┆            │
│      ┆               ┆               ┆ prvotřídní    ┆   ┆               ┆ - SSSR…       ┆ prvotřídní   ┆            │
│      ┆               ┆               ┆ jako…         ┆   ┆               ┆               ┆ ja…          ┆            │
│ 2008 ┆ původní česká ┆ Ústavní       ┆ Povinná       ┆ … ┆ právní        ┆               ┆ Ústavní      ┆ povinnosti │
│      ┆               ┆ právo.        ┆ mlčenlivost   ┆   ┆ předpisy      ┆               ┆ právo.       ┆            │
│      ┆               ┆ Správní právo ┆ zdravotnic…   ┆   ┆ příručky      ┆               ┆ Správní      ┆            │
│      ┆               ┆               ┆               ┆   ┆ legal…        ┆               ┆ právo P…     ┆            │
│ 1978 ┆ původní česká ┆               ┆ Reklamace     ┆ … ┆               ┆ Zboží -       ┆ Reklamace    ┆ povinnosti │
│      ┆               ┆               ┆ spotřebitelů  ┆   ┆               ┆ prodej -      ┆ spotřebitelů ┆            │
│      ┆               ┆               ┆ v obcho…      ┆   ┆               ┆ reklamace     ┆ v obc…       ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆ spo…          ┆              ┆            │
│ 1959 ┆ původní česká ┆               ┆ Jaké jsou     ┆ … ┆               ┆ Manželství -  ┆ Jaké jsou    ┆ povinnosti │
│      ┆               ┆               ┆ povinnosti    ┆   ┆               ┆ literatura -  ┆ povinnosti   ┆            │
│      ┆               ┆               ┆ manželů a…    ┆   ┆               ┆ sezn…         ┆ manželů…     ┆            │
│ 2011 ┆ překladová    ┆ Etika.        ┆ Soumrak       ┆ … ┆ eseje essays  ┆               ┆ Etika.       ┆ povinnosti │
│      ┆               ┆ Morální       ┆ povinnosti :  ┆   ┆               ┆               ┆ Morální      ┆            │
│      ┆               ┆ filozofie     ┆               ┆   ┆               ┆               ┆ filozofie    ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆               ┆ Soumr…       ┆            │
│ 1960 ┆ původní česká ┆ Železniční    ┆ Pokladní      ┆ … ┆ příručky      ┆               ┆ Železniční   ┆ povinnosti │
│      ┆               ┆ doprava       ┆ služba v      ┆   ┆               ┆               ┆ doprava      ┆            │
│      ┆               ┆               ┆ železniční s… ┆   ┆               ┆               ┆ Pokladní sl… ┆            │
│ 1925 ┆ původní česká ┆               ┆ Hrdinka       ┆ … ┆               ┆               ┆ Hrdinka      ┆ povinnosti │
│      ┆               ┆               ┆ povinnosti :  ┆   ┆               ┆               ┆ povinnosti : ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆               ┆ Julie V…     ┆            │
│ 1917 ┆ původní česká ┆ Organizace a  ┆ Pokyny o      ┆ … ┆               ┆               ┆ Organizace a ┆ povinnosti │
│      ┆               ┆ řízení        ┆ státních      ┆   ┆               ┆               ┆ řízení       ┆            │
│      ┆               ┆ veřejné sp…   ┆ vyživovacích… ┆   ┆               ┆               ┆ veřejné sp…  ┆            │
│ 1979 ┆ původní česká ┆               ┆ Cvičení z     ┆ … ┆               ┆ Matematika -  ┆ Cvičení z    ┆ povinnosti │
│      ┆               ┆               ┆ matematiky    ┆   ┆               ┆ příklady -    ┆ matematiky   ┆            │
│      ┆               ┆               ┆ pro 6. ro…    ┆   ┆               ┆ učebni…       ┆ pro 6. …     ┆            │
│ 1966 ┆ původní česká ┆ Mezinárodní   ┆ Co je         ┆ … ┆ brožury       ┆               ┆ Mezinárodní  ┆ povinnosti │
│      ┆               ┆ vztahy,       ┆ diplomacie /  ┆   ┆               ┆               ┆ vztahy,      ┆            │
│      ┆               ┆ světová po…   ┆               ┆   ┆               ┆               ┆ světová po…  ┆            │
│ 1968 ┆ původní česká ┆               ┆ Chraň se      ┆ … ┆               ┆ Zemědělství - ┆ Chraň se     ┆ povinnosti │
│      ┆               ┆               ┆ úrazu! :      ┆   ┆               ┆ zábrana       ┆ úrazu! :     ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆ úrazová …     ┆ Jaroslav V…  ┆            │
│ 2019 ┆ původní česká ┆ Česká próza   ┆ O umíněné     ┆ … ┆ české příběhy ┆               ┆ Česká próza  ┆ povinnosti │
│      ┆               ┆ Literatura    ┆ Andělce /     ┆   ┆ publikace pro ┆               ┆ Literatura   ┆            │
│      ┆               ┆ pro dět…      ┆               ┆   ┆ dě…           ┆               ┆ pro dět…     ┆            │
│ 1980 ┆ původní česká ┆               ┆ Počátky       ┆ … ┆               ┆ Školství      ┆ Počátky      ┆ povinnosti │
│      ┆               ┆               ┆ povinného     ┆   ┆               ┆ všeobecně     ┆ povinného    ┆            │
│      ┆               ┆               ┆ všeobecně vz… ┆   ┆               ┆ vzdělávací …  ┆ všeobecně …  ┆            │
│ 1967 ┆ původní česká ┆ Vývojová      ┆ Sborník prací ┆ … ┆ sborníky      ┆               ┆ Vývojová     ┆ povinnosti │
│      ┆               ┆ psychologie.  ┆ Pedagogické   ┆   ┆               ┆               ┆ psychologie. ┆            │
│      ┆               ┆ Individu…     ┆ faku…         ┆   ┆               ┆               ┆ Individu…    ┆            │
│ 1953 ┆ překladová    ┆               ┆ Politické     ┆ … ┆               ┆ Služba        ┆ Politické    ┆ povinnosti │
│      ┆               ┆               ┆ zajištění     ┆   ┆               ┆ strážní       ┆ zajištění    ┆            │
│      ┆               ┆               ┆ strážní sl…   ┆   ┆               ┆ sovět. -      ┆ strážní …    ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆ práce …       ┆              ┆            │
│ 2023 ┆ původní česká ┆ Komiksy.      ┆ Murie /       ┆ … ┆ české povídky ┆               ┆ Komiksy.     ┆ povinnosti │
│      ┆               ┆ Komiksové     ┆               ┆   ┆ sci-fi        ┆               ┆ Komiksové    ┆            │
│      ┆               ┆ adaptace      ┆               ┆   ┆ komiksy h…    ┆               ┆ adaptace Mu… ┆            │
│ 2020 ┆ původní česká ┆ Pracovní,     ┆ Přechod práv  ┆ … ┆ příručky      ┆               ┆ Pracovní,    ┆ povinnosti │
│      ┆               ┆ sociální,     ┆ a povinností  ┆   ┆ handbooks and ┆               ┆ sociální,    ┆            │
│      ┆               ┆ stavební p…   ┆ z pr…         ┆   ┆ manuals       ┆               ┆ stavební p…  ┆            │
│ 2003 ┆ původní česká ┆ Úkoly veřejné ┆ Úplné znění   ┆ … ┆ zákony laws   ┆               ┆ Úkoly        ┆ povinnosti │
│      ┆               ┆ správy,       ┆ Zákona České  ┆   ┆               ┆               ┆ veřejné      ┆            │
│      ┆               ┆ správní …     ┆ národ…        ┆   ┆               ┆               ┆ správy,      ┆            │
│      ┆               ┆               ┆               ┆   ┆               ┆               ┆ správní …    ┆            │
│ 1953 ┆ překladová    ┆ Zemědělství a ┆ Kolchozní     ┆ … ┆ brožury       ┆ Kolchozy -    ┆ Zemědělství  ┆ povinnosti │
│      ┆               ┆ příbuzné      ┆ usedlost /    ┆   ┆               ┆ hospodářství  ┆ a příbuzné   ┆            │
│      ┆               ┆ oblasti…      ┆               ┆   ┆               ┆ záhume…       ┆ oblasti…     ┆            │
│ 2024 ┆ překladová    ┆ Germánské     ┆ Pipi Dlouhá   ┆ … ┆ švédské       ┆               ┆ Germánské    ┆ povinnosti │
│      ┆               ┆ literatury    ┆ punčocha /    ┆   ┆ příběhy       ┆               ┆ literatury   ┆            │
│      ┆               ┆ Literatur…    ┆               ┆   ┆ publikace pro ┆               ┆ Literatur…   ┆            │
│      ┆               ┆               ┆               ┆   ┆ …             ┆               ┆              ┆            │
│ 1974 ┆ překladová    ┆               ┆ Nařízení o    ┆ … ┆               ┆ Podniky       ┆ Nařízení o   ┆ povinnosti │
│      ┆               ┆               ┆ úkolech,      ┆   ┆               ┆ socialistické ┆ úkolech,     ┆            │
│      ┆               ┆               ┆ právech a …   ┆   ┆               ┆ NDR - na…     ┆ právech …    ┆            │
│ 1978 ┆ původní česká ┆               ┆ Encyklopedie  ┆ … ┆               ┆ Manželství -  ┆ Encyklopedie ┆ povinnosti │

In [43]:
revoluce = {
    'povinnosti': '[Pp]ovinnost',
    'Ježíš': '[Jj]ežíš',
#    'volný čas': '[Vv]olný čas',
#    'přestavba': '[Pp]řestavb',
    'horoskopy': '([Hh]oroskop|[Zz]věrokru|[Aa]strolo)',
    'privatizace': '[Pr]ivatiza',
#    'kolektiv': '[Kk]olektiv',
#    'soukromník': '[Ss]oukrom(ý|ní)',
    'produktivita': '[Pp]roduktivi',
    'pionýr': ('[Pi]oný[rř]'),
    'skaut, junák': '([Ss]kaut|[Jj]uná[kc])',
    'spartakiáda': '[Ss]partakiá',
    'sokolský slet': '[Ss]okols\w{1,5}\sslet',
#    'solidarita': '[Ss]olid[áa]r',
#    'úspěchy': '[Úú]spě',
#    'demokracie': '[Dd]emokra',
#    'tyranie':'[Tt]yran',
    'RVHP': '(RVHP|Rad\w{1,5} vzájemné hospodářské pomoci)',
    'ES/EU':'(Evropsk\w{1,3}\suni\w{1,4}|Evropsk\w{1,3}\sspolečen)'
    
#    'solidarita': '[Ss]olid[aá]',
#    'zisk': '[Zz]isk',
#    'tradice':'[Tt]radi[cč]',
#    'sex': '[S]ex',
    #'Marx': '[Mm]arx',
    #'Masaryk': '[Mm]asaryk',
}

titulek = "Vybraná témata knih ve 20. století"
podtitulek = "Co tečka, to kniha: růžová původní, modrá překladová. (Včetně opakovaných vydání.)"

finalni_graf_data = pl.concat([hledej_tema(tema, retezec) for tema, retezec in revoluce.items()]).filter(pl.col("rok").is_between(1900,2000)).with_columns(
                   pl.col("rok").map_elements(
                       lambda x: datetime.date(year=x, month=1, day=1), 
                       return_dtype=pl.Date
                   ).cast(pl.Datetime)
               )
finalni_graf_data

temata_zlomy = alt.Chart(
    finalni_graf_data.to_pandas(), title=alt.Title(titulek,subtitle=podtitulek)
).mark_circle(size=6, opacity=1).encode(
    x=alt.X("rok:T", title=None, axis=alt.Axis(domainOpacity=0, tickColor='#ECEDE6', tickCount=8)), 
    y=alt.Y('téma:N', 
            title=None, 
            axis=alt.Axis(domainOpacity=0, tickColor='white'),
            sort=[tema for tema, neco in revoluce.items()]), 
            yOffset=alt.YOffset("jitter:Q", scale=alt.Scale(range=[2, 15])), 
            color=alt.Color('preklad:N', scale=alt.Scale(range=['#E09DA3','#81A9D5']), 
            sort=[tema for tema, retezec in revoluce.items()]
).legend(None)
).transform_calculate(jitter="sqrt(-2*log(random()))*cos(2*PI*random())")

rulecolor = '#81A9D5'

rule1 = alt.Chart(alt.Data(values=[{'rok': '1948-02-25'}])).mark_rule(
    color=rulecolor,
    strokeDash=[1.5, 4]  # Optional: makes the line dashed
).encode(
    x='rok:T'
)

rule2 = alt.Chart(alt.Data(values=[{'rok': '1989-11-17'}])).mark_rule(
    color=rulecolor,
    strokeDash=[1.5, 4]  # Optional: makes the line dashed
).encode(
    x='rok:T'
)

# Add text annotation
text1 = alt.Chart(alt.Data(values=[{'rok': '1948-02-25', 'y': 0.3}])).mark_text(
    # angle=270,  # Rotates text vertically
    align='right',
    baseline='middle',
    dy=70,# Slight horizontal offset from the line
    dx=-6.5,
    text=['komunistický','převrat →'],
    font='Asap',
    size=8
).encode(
    x='rok:T',
    y=alt.value(0)  # Places text at bottom of chart
)


# Add text annotation
text2 = alt.Chart(alt.Data(values=[{'rok': '1989-11-17', 'y': 0.3}])).mark_text(
    # angle=270,  # Rotates text vertically
    align='right',
    baseline='middle',
    dy=73,# Slight horizontal offset from the line
    dx=-6.5,
    text=['sametová revoluce →'],
    font='Asap',
    size=8
).encode(
    x='rok:T',
    y=alt.value(0)  # Places text at bottom of chart
)

# Add text annotation
text3 = alt.Chart(alt.Data(values=[{'rok': '1918-10-28', 'y': 0.3}])).mark_text(
    # angle=270,  # Rotates text vertically
    align='right',
    baseline='middle',
    dy=70,# Slight horizontal offset from the line
    dx=-6.6,
    text=['založení','ČSR →'],
    font='Asap',
    size=8
).encode(
    x='rok:T',
    y=alt.value(0)  # Places text at bottom of chart
)

rule3 = alt.Chart(alt.Data(values=[{'rok': '1918-10-28'}])).mark_rule(
    color=rulecolor,
    strokeDash=[1.5, 4]  # Optional: makes the line dashed
).encode(
    x='rok:T'
)

temata_zlomy_komb = (temata_zlomy + rule1 + rule2 + rule3 + text1 + text2 + text3).properties(
    width=kredity['sirka'] * 1.2, autosize={'type': 'fit', 'contains': 'padding'}
).configure_view(stroke='transparent').configure_axisX(grid=False, domain=False)

temata_zlomy_komb

alt.LayerChart(...)

In [45]:
me_to_neurazi(temata_zlomy_komb, kredity=kredity['default'], soubor="01_temata")

<figure>
    <a href="https://data.irozhlas.cz/knihy-grafy/01_temata.svg" target="_blank">
    <img src="https://data.irozhlas.cz/knihy-grafy/01_temata.svg" width="100%" alt="Omlouváme se, ale alternativní text se nepodařilo vygenerovat. Texty v grafu by měly být čitelné ze zdrojového souboru SVG." />
    </a>
    </figure>

## Hrajeme na přání

In [54]:
na_prani = { 'Tibet':'[Tt]ibet'
}

na_prani_data = pl.concat([hledej_tema(tema, retezec) for tema, retezec in na_prani.items()]).filter(pl.col("rok").is_between(1900,2000)).with_columns(
                   pl.col("rok").map_elements(
                       lambda x: datetime.date(year=x, month=1, day=1), 
                       return_dtype=pl.Date
                   ).cast(pl.Datetime)
               )

na_prani_graf = alt.Chart(
    na_prani_data.to_pandas(), title=alt.Title("Graf na přání"), width=kredity['sirka'] * 1.2
).mark_circle(size=6, opacity=1).encode(
    x=alt.X("rok:T", title=None, axis=alt.Axis(domainOpacity=0, tickColor='#ECEDE6', tickCount=8)), 
    y=alt.Y('téma:N', 
            title=None, 
            axis=alt.Axis(domainOpacity=0, tickColor='white'),
            sort=[tema for tema, neco in revoluce.items()]), 
            yOffset=alt.YOffset("jitter:Q", scale=alt.Scale(range=[2, 15])), 
            color=alt.Color('preklad:N', scale=alt.Scale(range=['#E09DA3','#81A9D5']), 
            sort=[tema for tema, retezec in revoluce.items()]
).legend(None)
).transform_calculate(jitter="sqrt(-2*log(random()))*cos(2*PI*random())")

na_prani_graf

alt.Chart(...)

In [60]:
hledej_tema('skaut, junák', '([Ss]kaut|[Jj]uná[kc])').filter(pl.col("rok").is_between(1949,1967)).sort(by="rok")

shape: (27, 22)
┌──────┬───────────────┬───────────────┬───────────────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ rok  ┆ preklad       ┆ 072_x         ┆ 245_a         ┆ … ┆ 655_a        ┆ 964_a        ┆ keywords     ┆ téma         │
│ ---  ┆ ---           ┆ ---           ┆ ---           ┆   ┆ ---          ┆ ---          ┆ ---          ┆ ---          │
│ i64  ┆ str           ┆ str           ┆ str           ┆   ┆ str          ┆ str          ┆ str          ┆ str          │
╞══════╪═══════════════╪═══════════════╪═══════════════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 1949 ┆ původní česká ┆               ┆ Napucánek /   ┆ … ┆              ┆ Zakarpatská  ┆ Napucánek /  ┆ skaut, junák │
│      ┆               ┆               ┆               ┆   ┆              ┆ Ukrajina -   ┆ Josef Spilka ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ vyprávě…     ┆ ; I…         ┆              │
│ 1949 ┆ původní česká ┆               ┆ Táborový      ┆ … ┆              ┆ Wolker, Jiří ┆ Táborový     ┆ skaut, junák │
│      ┆               ┆               ┆ deník šestnác ┆   ┆              ┆ (1900-1924   ┆ deník šestná ┆              │
│      ┆               ┆               ┆ tiletého…     ┆   ┆              ┆ čes. b…      ┆ ctileté…     ┆              │
│ 1949 ┆ původní česká ┆               ┆ Vodáci z      ┆ … ┆              ┆ Moře         ┆ Vodáci z     ┆ skaut, junák │
│      ┆               ┆               ┆ Olivové       ┆   ┆              ┆ Jaderské -   ┆ Olivové      ┆              │
│      ┆               ┆               ┆ zátoky :      ┆   ┆              ┆ knihy pro    ┆ zátoky : Ad… ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ mlád…        ┆              ┆              │
│ 1949 ┆ původní česká ┆               ┆ Zápisník      ┆ … ┆              ┆ Junáci -     ┆ Zápisník     ┆ skaut, junák │
│      ┆               ┆               ┆ časopisu      ┆   ┆              ┆ kalendáře    ┆ časopisu     ┆              │
│      ┆               ┆               ┆ Vpřed [na ro… ┆   ┆              ┆ Kalendáře    ┆ Vpřed [na …  ┆              │
│ 1950 ┆ původní česká ┆               ┆ Pojďte s      ┆ … ┆              ┆ Junáci -     ┆ Pojďte s     ┆ skaut, junák │
│      ┆               ┆               ┆ pionýry :     ┆   ┆              ┆ pionýři      ┆ pionýry :    ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ Pionýři POJ  ┆ zpracoval…   ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ (…           ┆              ┆              │
│ 1950 ┆ překladová    ┆               ┆ Stará pevnost ┆ … ┆              ┆ Ukrajina -   ┆ Stará        ┆ skaut, junák │
│      ┆               ┆               ┆ /             ┆   ┆              ┆ boje s       ┆ pevnost /    ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ petljurovci  ┆ Vladimír     ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ …            ┆ Bel…         ┆              │
│ 1951 ┆ překladová    ┆               ┆ Létající      ┆ … ┆              ┆ Pohádky      ┆ Létající     ┆ skaut, junák │
│      ┆               ┆               ┆ koráb a jiné  ┆   ┆              ┆ ruské        ┆ koráb a jiné ┆              │
│      ┆               ┆               ┆ pohádky …     ┆   ┆              ┆              ┆ pohádk…      ┆              │
│ 1951 ┆ překladová    ┆               ┆ O junákovi s  ┆ … ┆              ┆ Pohádky      ┆ O junákovi s ┆ skaut, junák │
│      ┆               ┆               ┆ planoucím     ┆   ┆              ┆ symbolické   ┆ planoucím    ┆              │
│      ┆               ┆               ┆ srdcem …      ┆   ┆              ┆              ┆ srdce…       ┆              │
│ 1952 ┆ původní česká ┆               ┆ Korespondence ┆ … ┆              ┆ Wolker, Jiří ┆ Korespondenc ┆ skaut, junák │
│      ┆               ┆               ┆ s rodiči /    ┆   ┆              ┆ (1900-1924   ┆ e s rodiči / ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ básník…      ┆ Jiř…         ┆              │
│ 1952 ┆ překladová    ┆               ┆ Stateční      ┆ … ┆              ┆ Hrdinové -   ┆ Stateční     ┆ skaut, junák │
│      ┆               ┆               ┆ junáci :      ┆   ┆              ┆ pohádky      ┆ junáci : Z   ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ národů SSSR… ┆ rus. pův…    ┆              │
│ 1953 ┆ původní česká ┆ Výchova a     ┆ Pionýrská     ┆ … ┆ příručky     ┆ Pionýři -    ┆ Výchova a    ┆ skaut, junák │
│      ┆               ┆ vzdělávání    ┆ organisace :  ┆   ┆              ┆ organizace   ┆ vzdělávání   ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ pionýrská…   ┆ Pionýrská…   ┆              │
│ 1953 ┆ původní česká ┆ Výchova a     ┆ Skauting ve   ┆ … ┆ brožury      ┆              ┆ Výchova a    ┆ skaut, junák │
│      ┆               ┆ vzdělávání    ┆ službách      ┆   ┆              ┆              ┆ vzdělávání   ┆              │
│      ┆               ┆               ┆ podněcova…    ┆   ┆              ┆              ┆ Skauting …   ┆              │
│ 1953 ┆ původní česká ┆ Česká poezie  ┆ Alšova vlast  ┆ … ┆ česká poezie ┆ Aleš,        ┆ Česká poezie ┆ skaut, junák │
│      ┆               ┆               ┆ :             ┆   ┆              ┆ Mikoláš      ┆ Alšova vlast ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ (1852-1913   ┆ : La…        ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ malíř…       ┆              ┆              │
│ 1954 ┆ původní česká ┆               ┆ Černohorští   ┆ … ┆              ┆ Miljanov,    ┆ Černohorští  ┆ skaut, junák │
│      ┆               ┆               ┆ junáci /      ┆   ┆              ┆ Marko        ┆ junáci /     ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ (1833-1901   ┆ Josef H…     ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ voj…         ┆              ┆              │
│ 1955 ┆ překladová    ┆ Literatura    ┆ Lovec Charibu ┆ … ┆ pohádky      ┆ Pohádky      ┆ Literatura   ┆ skaut, junák │
│      ┆               ┆ pro děti a    ┆ /             ┆   ┆ publikace    ┆ národů SSSR  ┆ pro děti a   ┆              │
│      ┆               ┆ mládež (…     ┆               ┆   ┆ pro děti     ┆ Pohádky vý…  ┆ mládež (…    ┆              │
│ 1957 ┆ původní česká ┆ Česká próza   ┆ Ztracená      ┆ … ┆ české        ┆ Povídky      ┆ Česká próza  ┆ skaut, junák │
│      ┆               ┆ Literatura    ┆ stopa /       ┆   ┆ povídky      ┆ dobrodružné  ┆ Literatura   ┆              │
│      ┆               ┆ pro dět…      ┆               ┆   ┆ publikace    ┆ pro mládež   ┆ pro dět…     ┆              │
│      ┆               ┆               ┆               ┆   ┆ pro dě…      ┆              ┆              ┆              │
│ 1958 ┆ překladová    ┆               ┆ Jugoslávské   ┆ … ┆              ┆ Písně lidové ┆ Jugoslávské  ┆ skaut, junák │
│      ┆               ┆               ┆ zpěvy :       ┆   ┆              ┆ jugoslávské  ┆ zpěvy :      ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ - výb…       ┆ vybral, …    ┆              │
│ 1958 ┆ překladová    ┆               ┆ Jugoslávské   ┆ … ┆              ┆ Písně lidové ┆ Jugoslávské  ┆ skaut, junák │
│      ┆               ┆               ┆ zpěvy :       ┆   ┆              ┆ jugoslávské  ┆ zpěvy :      ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ - výb…       ┆ vybral, …    ┆              │
│ 1958 ┆ překladová    ┆               ┆ Diamantová    ┆ … ┆              ┆ Pohádky      ┆ Diamantová   ┆ skaut, junák │
│      ┆               ┆               ┆ sekera :      ┆   ┆              ┆ baltské      ┆ sekera : z   ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ Pohádky      ┆ rus. o…      ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ národů…      ┆              ┆              │
│ 1959 ┆ původní česká ┆               ┆ Tři orlí pera ┆ … ┆              ┆ Skauti       ┆ Tři orlí     ┆ skaut, junák │
│      ┆               ┆               ┆ /             ┆   ┆              ┆ dělničtí -   ┆ pera /       ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ ČSR          ┆ [Autor:]     ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ předmnic…    ┆ Jan…         ┆              │
│ 1959 ┆ původní česká ┆               ┆ Zlín 22 -     ┆ … ┆              ┆ Letadla      ┆ Zlín 22 -    ┆ skaut, junák │
│      ┆               ┆               ┆ Junák :       ┆   ┆              ┆ sportovní    ┆ Junák :      ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ (modely) -   ┆ konstrukce…  ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ k…           ┆              ┆              │
│ 1960 ┆ překladová    ┆               ┆ Kolo          ┆ … ┆              ┆ Pohádky      ┆ Kolo         ┆ skaut, junák │
│      ┆               ┆               ┆ bulharských   ┆   ┆              ┆ bulharské    ┆ bulharských  ┆              │
│      ┆               ┆               ┆ pohádek /     ┆   ┆              ┆              ┆ pohádek / R… ┆              │
│ 1962 ┆ překladová    ┆ Literatura    ┆ Junácký zápas ┆ … ┆ slovenské    ┆              ┆ Literatura   ┆ skaut, junák │
│      ┆               ┆ pro děti a    ┆ :             ┆   ┆ pověsti      ┆              ┆ pro děti a   ┆              │
│      ┆               ┆ mládež (…     ┆               ┆   ┆ publikace    ┆              ┆ mládež (…    ┆              │
│      ┆               ┆               ┆               ┆   ┆ pr…          ┆              ┆              ┆              │
│ 1963 ┆ původní česká ┆               ┆ Tři orlí pera ┆ … ┆              ┆ Skauti       ┆ Tři orlí     ┆ skaut, junák │
│      ┆               ┆               ┆ /             ┆   ┆              ┆ dělničtí -   ┆ pera / Jan   ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ ČSR          ┆ Mareš ; …    ┆              │
│      ┆               ┆               ┆               ┆   ┆              ┆ předmnic…    ┆              ┆              │
│ 1964 ┆ původní česká ┆               ┆ Spartakovi    ┆ … ┆              ┆ Spartakovi   ┆ Spartakovi   ┆ skaut, junák │
│      ┆               ┆               ┆ skauti práce  ┆   ┆              ┆ skauti práce ┆ skauti práce ┆              │
│      ┆               ┆               ┆ :             ┆   ┆              ┆ - Čech…      ┆ :   …        ┆              │
│ 1966 ┆ původní česká ┆               ┆ Dětské hnutí  ┆ … ┆              ┆ Skauting čs. ┆ Dětské hnutí ┆ skaut, junák │
│      ┆               ┆               ┆ v Českosloven ┆   ┆              ┆ - vývoj -    ┆ v Českoslove ┆              │
│      ┆               ┆               ┆ sku …         ┆   ┆              ┆ rok 194…     ┆ nsk…         ┆              │
│ 1967 ┆ původní česká ┆ Sport. Hry.   ┆ Proletářská   ┆ … ┆ sborníky     ┆              ┆ Sport. Hry.  ┆ skaut, junák │
│      ┆               ┆ Tělesná       ┆ tělovýchova a ┆   ┆ konferencí   ┆              ┆ Tělesná      ┆              │
│      ┆               ┆ cvičení       ┆ boj …         ┆   ┆              ┆              ┆ cvičení Pr…  ┆              │
└──────┴───────────────┴───────────────┴───────────────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘

In [62]:
hledej_tema('skaut, junák', '([Ss]kaut|[Jj]uná[kc])').filter(pl.col("rok").is_between(1949,1967)).sort(by="rok").write_csv("data/skaut-junak.csv")