In [1]:
import os
import datetime
import polars as pl
import pandas as pd
pl.Config(tbl_rows=100)
from src.najdi_rok import najdi_rok
from src.pocet_stran import pocet_stran
from src.bez_bordelu import bez_bordelu
from src.alt_friendly import alt_friendly
from src.zjisti_vazbu import zjisti_vazbu

In [2]:
df = pl.read_parquet(os.path.join("data/cnb_sloupce","100.parquet"))
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","leader.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","008.parquet")), left_on="001", right_on="001", how="left")
df = df.to_pandas()
df = df[df["leader"].str[6].isin(["a", "t"])]
df = df[~df["leader"].str[7].isin(["b", "i", "s", " "])]
df = df[(df["008"].str[15:17] == "xr") & (df["008"].str[35:38] == "cze")]
df = pl.from_pandas(df)
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","020.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","022.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","245.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","300.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","655.parquet")), left_on="001", right_on="001", how="left")
df = df.join(pl.read_parquet(os.path.join("data/cnb_sloupce","700.parquet")), left_on="001", right_on="001", how="left")
df = df.explode("022_a").filter(pl.col("022_a").is_null())
df = df.with_columns(pl.col('008').map_elements(najdi_rok, return_dtype=int).alias('rok'))
df = df.with_columns(pl.col('300_a').map_elements(pocet_stran, return_dtype=int).alias('stran'))
df = df.with_columns(pl.col('245_a').map_elements(bez_bordelu, return_dtype=str))
df = df.explode("020_q").with_columns(pl.col("020_q").map_elements(zjisti_vazbu, return_dtype=str).alias('vazba'))
df = df.explode('245_p').with_columns(pl.col('245_p').map_elements(bez_bordelu, return_dtype=str))
print(len(df))
df = df.filter(pl.col("rok") >= 1800)

df = df.filter((~pl.col("245_h").str.contains("grafika")) | pl.col("245_h").is_null()).unique(subset=["008","100_a","245_a","245_p"], keep="first")
print(len(df))

795736
705921

In [3]:
import requests
from bs4 import BeautifulSoup

## Le Monde's 100 Books of the Century

In [5]:
r = requests.get("https://en.wikipedia.org/wiki/Le_Monde%27s_100_Books_of_the_Century")
soup = BeautifulSoup(r.text)
tabulka_monde = soup.find(class_="sortable")

In [6]:
for radek in tabulka_monde.find_all("tr"):
    try:
        autor = radek.find_all("td")[2].text.strip().split(' ')[-1]
        print(f"{autor}: {radek.find_all("td")[1].text.strip()}")
        print(', '.join(set(df.filter(pl.col('100_a').str.contains(autor)).select(pl.col('245_a')).to_series().to_list())))
        print('***')
    except:
        pass

Camus: The StrangerThe Outsider
Nedorozumění, Exil a království, Vyprávění severoamerických indiánů, Eseje, Svět Židů, Léto, Romány a povídky, Člověk revoltující, Spravedliví, Caligula, Cizinec, Pád, Zápisníky II, První člověk, Mor, Velká výměna, Zápisníky III, Zápisníky I, Král Roman, Mýtus o Sisyfovi, Šťastná smrt
***
Proust: In Search of Lost TimeRemembrance of Things Past
Eseje, Dnové četby, Myšlenky, Hledání ztraceného času, Radosti a dny, Vzpomínky, Swannova láska, Jean Santeuil
***
Kafka: The Trial
Všeobecně užitečný stavitelský rádce při všech rozpočtech prací a potřeb stavebních, Básník Bernard Kosiner a jeho svět, Studie a úvahy o německé literatuře, Betlemáři, Průvodce pro interní audit a risk management, Šumava a Pošumaví, Malované na skle, Proces o hubičku, Zakletý ostrůvek, Střední Polabí, Příčiny úmrtí chirurgicky léčených dětí, Moře, Logo & corporate identity, Vliv vybraných podmínek na hmotnou a hodnotovou výtěž řeziva a na průchodnost pilařských linek, Hanuš Thein, Stručný zeměpis pro školy obecné, Sobotka, Řeka zpívá, Verše v roce, Král šibalů, aneb, Enšpíglova čtveráctví, Při stavbě čínské zdi, Tajemství emulze, Davídkovo léto s dědou, Nový židovský hřbitov, Obří krtek, Vincenz Janke, Židovské anekdoty, Kopytníci země české žijící i vyhynulí, Přátelé velkých činů, Interakční uživatelské systémy v ASŘ FMHTS-federální ministerstvo hutnictví a těžkého strojírenství, Leopardi v chrámu, Věřte mi, Zrcadlo, Funkční trénink, Amerika, Dopisy rodině, Živé ploty, 350 ženských povolání, Ateliér života, Die Verwandlung, Pozorování, Pojizeří a Prachovské skály u Jičína, Právo rodinné, Byli jednou dva, Jak pejsek hledal muzikanty, Železné a Žďárské Hory, Ochrana duševního zdraví prací, odpočinkem a zábavou, Deníky z cest, Parapsychologie, Aranžérské materiály a jejich zpracování, Proměna a jiné povídky, Mapa duše, mapa života, Květiny a svět, Lidové podmalby na skle, Akvarium, jeho živočišstvo a rostlinstvo, Bohumil Kafka, B. Kafka členům Spolku Žižkova pomníku a rozhodčímu soudu odborných znalců O soše Jana Žižky určené před Pantheon národního osvobození na vrchu Žižkově, Úsporné topení při nedostatku paliva, Aforismy, Lidové podmalby na skle ve sbírkách Ostravského muzea, Sladkovodní mechovky země České, Ve znamení Gorgóny, Stručná pediatrická chirurgie, Levná zelenina jako důležitá pomůcka výživy, Anděl strážný, Šípková Růženka, Mistři života, Na dřevě malované, Hanuš Fantl - neumlčený básník, Orlické hory, Nové základy experimentální psychologie, Proměna, Praktický návod zahradníka, Obrázky malované na skle ze sbírek Slezského zemského muzea, Základy videotvorby, Starý list, Tajemství zlatodolu, Pohádka o Honzovi, O duševně chorých v lidské společnosti, Levní dodavatelé masa, sádla, másla, mléka, sýra a vajec, Pojizeří a Prachovské skály, Základy teoretické mikroreologie heterogenních látek, Automatizované rozhodování v pilařském výrobním procesu, Chemoterapie zhoubného bujení, -ze sedla kola, Doupě, O psychobiologickém výzkumu v kriminologii, Lidové obrázky na skle z jižních a západních Čech, Hup a Hop, Dopisy Robertovi, Deníky 1913-1923, Dopisy přátelům a jiná korespondence, Letnění, hnojení a osévání rybníků, Rodinný dům, Zemětřesení, Posázaví, Povídky, Dopisy Mileně, Technika ve výkladní skříni, Dopis otci, Studie v oboru třetihorního útvaru v Čechách, Geologie a nauka o ložiskách pro 2. roč. průmyslové školy hornické, 4leté, Dopis otci a jiné částečné povídky, Můj vlas na řece Misůri, Technická cvičení, Předstih a předklon rámové pily, Geologie a nauka o ložiskách, Průvodce africkou výstavou cestovatele Dra. Emila Holuba, Proces, Greyhound story, aneb, Cesta kolem Ameriky za 50 dnů, Človek zítřka, Sobotka, Humprecht, Pásmo, O umělecké tvořivosti, Krutá léta, Hlodavci země české žijící i fossilní, Praha, hlava království Českého, Pediatrická chirurgie, Pověsti a povídačky z kraje pod Komoncem, Kafka, Schamoni, Portman, Člověk zítřka, V hodině velké zkoušky, Isabella, Osvobození Českolipska Sovětskou armádou v květnu 1945, Smrtelný omyl, Okolí Prahy, Zpráva o studijní cestě podniknuté podporou Zemského výboru království Českého a c.k. ministerstva orby ve Vídni, V krajích věčného ledu, Zámek, Kultura rozumu a vůle, Moderní tajemník lásky aneb Rádce milenců, Smrčiny, Hory Karlovarské a Doupovské, Deníky 1909-1912, Česko-saské Švýcarsko, Heinrich Heine, Technologie II, Josef Jambor, Vor medúzy, Ze světa, Franz Kafka, Vcházím do pokoje a vidím-, Jak Lucka vysvobodila prince Pašajdu, Podmalby na skle ze sbírek Muzea v Bruntále, Astronom, Rozpustilé holky ve škole, Láska je cesta, Venkovský lékař, Domácí vševěd, Pohádky z děravé kapsy, Seznam železničních stanic Československé republiky, Hvězda manéže, Dopisy Ottle a rodině, Smrt následníka, Plzeň s okolím a Český les, České Středohoří, Dopisy Felici, O tom, Mořské ryby na pražském trhu, Jak se mámí myš, Potraviny (maso, zrniny, zeleniny, ovoce), pochutiny a léky, jež možno v přírodě si opatřiti zdarma, Krušné Hory, Cvičení z chemie, Dopisy rodičům z let 1922-1924, Úsporná výživa hospodářská a zdravotní reforma výživy, jídelního lístku, vaření a zažívání nejen se zřetelem na nutná obmezení v době války, nýbrž i se zřetelem na hospodářské a zdravotní povznesení lidu, Význam ochrany a bezpečnosti IS-IT pro konkurenceschopnost podniku, Thomas Mann, Šest mužů s fantazií, Chaloupky naše, Svítání v duši, Snižování nákladů v metalurgii, Plochostropý hranostaj, Rozpravy o Belmondě, Kvaše, Ze svatého koutu světnic, Zahrádka při domě rodinném, Akce StB Polom, Člověk zítřka - kultura rozumu a vůle, Popis jednoho zápasu, Večeře s vrahem, Cardinal Sin, Ortel, Míčové hry, Šelmy (Carnivora) země české, žijící i fossilní, Z tajů života, Zpráva pro akademii, Květinářství, 99m Tc-dextran, Vánoční legenda z Ghetta, Jak předcházet srdečním chorobám, Nezvěstný (Amerika), O chovu salmonidů, Barva Paříže, Život naživo, Minulost je mrtvá, život začal právě teď, Brda a Podbrdí, Obzory, Příklady a úlohy z obecné, anorganické a organické chemie, 33 zastavení, Dárek z pouti, Českomoravská vysočina, O vodách, které přestaly zpívat, Lužické Hory a Ještěd, Velký pražský rabi Jehuda Löw, Krkonoše a Jizerské Hory, Řeka v prstech, Spanilá kajicnice, Výzkumy zvířeny ve vodách českých, Hup a Hop na moři, Levné pokrmy zeleninové, Levné obědy a večeře, Střední Povltaví a středočeské žulové pohoří, Kulda Kulíšek, Pamětní spis o zoologické a akklimatační zahradě v Praze, Technologie obrábění, Noční dobrodružství, Jiří Purkyně, bojovník, Praktický návod pro zahradníka, Pediatrická chirurgie 1963, Lidové podmalby na skle ze sbírek Regionálního muzea v Náchodě, Ty jsi můj anděl z nebe, Výbuch v podzemním jezeře, Z uhelných dolů ostravských, Pepříčky, Řešení napjatosti v periodicky nestejnorodém vrstevnatém prostředí, Ivan Kafka, Ivan Kafka 1975-2005, --ze sedla kola, Nezvěstný, Žíznivá poutnice, Pojištění dělníků a výkonných úředníků pro případ nemoci podle rakouského zákonodárství s nálezy správního soudu od roku 1889 do roku 1903, Největší sluha člověka - slon, Humprecht - zámek
***
Saint-Exupéry: The Little Prince
Země lidí, Letec a živly, Dopis rukojmímu, Saint-Exupéry, Slova jako hvězdy, Dopisy matce, Tanečnice Manon a jiné drobné texty, Moje planeta, Paměti růže, Štěstí, Noční let, Válečný pilot, Válečné zápisy, Kouzlo krajiny a moudrost slova, Kurýr na jih, Antoine de Saint-Exupéry, Povídky, Čistá smrt, Kameny chrámu, Malý princ, Pode mnou země, Země člověka, Citadela, Já a můj syn
***
Malraux: Man's Fate
Cesta královská, Léta ponížení, Imaginární muzeum, Naděje, Lidský úděl, Dobyvatelé
***
Céline: Journey to the End of the Night
Od zámku k zámku, Montessori pedagogika na doma, Skočná, Cesta na konec noci, Klaun's band II, Cesta do hlubin noci, Církev, Sever, Dítě a přírodní zákony, Škola mrtvol, Neexistující muzeum, Emma ve světě fantazie, Féerie pro jindy, Klaun's band I, Smrt na úvěr, Cena za dokonalost, Kincugi
***
Steinbeck: The Grapes of Wrath
Sladký čtvrtek, Na Plechárně, Byla kdysi válka, Činy krále Artuše a jeho vznešených rytířů, Červený koníček, Na plechárně, Toulky s Charleym za poznáním Ameriky, Bitva, --jejich je království nebeské, Měsíc zapadá, Perla, Na východ od ráje, Zima úzkosti, Ryzáček, Hrozny hněvu, Nebeské pastviny, Slunce a víno chudých, O myších a lidech, Toulavý autobus, Neznámému bohu, O Americe a Američanech, Pohár zlata, Pláň Tortilla, Ve stínu cypřiše, Čistý plamen
***
Hemingway: For Whom the Bell Tolls
Pátá kolona, Sbohem, armádo!, Sbohem armádo!, Stařec a moře, Mít a nemít, Neporažený, Komu zvoní hrana, Sbohem, armádo, Ostrovy uprostřed proudu, Pravda za rozbřesku, Slunce vyšlo, Pohyblivý svátek, Povídky, Neviditelná dívka, Přes řeku a do lesů, Pět stováků, Rajská zahrada, I slunce vychází, Hemingwayové, Zelené pahorky africké, Hrob Alexandra Velikého, Mít i nemít, Fiesta, Přes řeku do stínu stromů, Nebezpečné léto, Smrt odpoledne
***
Alain-Fournier: Le Grand Meaulnes
Portrét, Kouzelné dobrodružství, Veliký Meaulnes
***
Vian: Froth on the Daydream
Budovatelé říše, Jak kázal Vianney o svaté zpovědi, Růženec se svatým Janem Marií Vianneyem, Podšité chvilky, Průvodce po Saint-Germain-des-Prés, Červená tráva, Motolice a plankton, Zabte ošklivé, I tak kázal Vianney, Mravenci, Z myšlenek sv. Jana Marie Vianneye, Vlkodlak, Podzim v Pekingu, Boris Vian, Naplivu na vaše hroby, Holky nemaj ponětí-, Pěna dní, Krutá dobrodružství, U mrtvých na barvě kůže nesejde, Holky nemaj ponětí, Pier Paolo Pasolini a jeho filmy, Tak kázal Vianney, Srdcerváč, Flanďákova koupel, Rozruch v Andénách, Člověk tomu neunikne
***
Beauvoir: The Second Sex
Velice lehká smrt, Rozhovor s Jean-Paulem Sartrem, Mandaríni, Nerozlučné, Zlomená žena, Druhé pohlaví, Líbivé obrázky, Otrokyně, Pozvaná, Krev těch druhých, Paměti spořádané dívky
***
Beckett: Waiting for Godot
Jídlo, víno, přátelé, Novely a texty pro nic, Molloy, Katastrofa a jiná dramátka, Biologie, Poslední páska, O sýrech, Eseje, Toulky světem malířství, 1000 nejkrásnějších obrazů historie, Vaříme z vlastních zásob, Čekání na Godota, Evoluce, Chladný popel, Murphy, Malone umírá, Nepojmenovatelný, Tso, Konec hry, První láska, Chemie smrti, Texty pro nic
***
Sartre: Being and Nothingness
Holá pravda, Sešity z podivné války, Nevolnost, Bytí a nicota, S vyloučením veřejnosti, Slova, Vězňové z Altony, 5 her a jedna aktovka, Dramata, Zeď, Uragán nad cukrem, Marxismus a existencialismus, Existencialismus je humanismus, Mouchy, Cesty k svobodě, Vědomí a existence
***
Eco: The Name of the Rose
Umění a krása ve středověké estetice, Otevřené dílo, O televizi, Tajemný plamen královny Loany, O literatuře, Mysl a smysl, Na ramenech obrů, Tři příběhy, Teorie sémiotiky, Od stromu k labyrintu, Kant a ptakopysk, Hledání dokonalého jazyka v evropské kultuře, Ostrov včerejšího dne, Od hlouposti k šílenství, Skeptikové a těšitelé, Foucaultovo kyvadlo, Jméno růže, Nulté číslo, Migrace a nesnášenlivost, Vytváření nepřítele a jiné příležitostné texty, Svět podle Číny, Baudolino, Zpověď mladého romanopisce, Bludiště seznamů, Poznámky na krabičkách od sirek, Pro kluky, Dějiny legendárních zemí a míst, Jak cestovat s lososem, Časové otázky finanční politiky, Pražský hřbitov, Šest procházek literárními lesy, Jak napsat diplomovou práci, Lector in fabula, O zrcadlech a jiné eseje, Meze interpretace
***
Solzhenitsyn: The Gulag Archipelago

***
Prévert: Paroles
Není se čeho bát, Pro tebe, má lásko, Slova, Nejkratší písně, Jako zázrakem, Seulement come ça, Pohádky pro nehodné děti, Nadosmrti dítětem, Jsem jaký jsem, Divadelní hříčky, Jen tak
***
Apollinaire: Alcools
Hrdinské činy mladého donchuána, Píseň nemilovaného, Pásmo, Sedící žena, Kaligramy, Noané?, Zavražděný básník, Hrdinské činy mladého Dona Juana, Hudebník ze Saint-Merry, Básně, Alkoholy života, Básně - obrazy, Zóna, Pražský chodec, O novém umění, Zahnívající čaroděj, Budu tě čekat všude na světě, Pahorky, Předmluva k dílu markýze de Sade, Alfred Jarry, Apollinaire známý a neznámý, Prsy Tiresiovy, Alkoholy, Kacíř & spol., 11 tisíc prutů, aneb, Rychtářovy lásky, Básně Guillaumea Apollinairea, Zlá je naděje, Fantasie, Kacíř a spol., Pásmo a jiné verše, Ubrousek básníků, Deník 1898-1918, Tiréziovy prsy, Pastýřka Eiffelka, Stín mé lásky
***
Hergé: The Blue Lotus
Tintin a alf-art, Tintin, neohrožený reportér, v zemi Sovětů, Krab se zlatými klepety, Tajemství Jednorožce, První kroky na Měsíci, Tintin v zemi černého zlata, Faraonovy doutníky, Chrám Slunce, Záhadný paprsek, Tintin v Americe, Žezlo krále Ottokara, Let 714 do Sydney, Záhadná hvězda, Černý ostrov, Stratoplán H 22, Míříme na Měsíc, Tintin a los Pícaros, Případ Hluchavka, Poklad rudého raubíře, Hadí soutěska, Šperky madam Castafiore, 7 křišťálových koulí, Tintin v Kongu, Tintin v Tibetu, Ulomené ucho, Poklad Rudého Rackhama, Modrý lotos, Koks na palubě
***
Frank: The Diary of a Young Girl

Nevyšlo:
- Colette: The Tendrils of the Vine- Duras: The Ravishing of Lol Stein
- Sarraute: Tropisms- Renard: Journal, 1887–1910- Lacan: Écrits
- Cendrars: Moravagine- Simenon: The Strange Case of Peter the Lett
- Genet: Our Lady of the Flowers- Char: Furor and Mystery
- Jacobs: Blake and Mortimer
- Butor: Second Thoughts
- Perse: Amers

Vyšlo, není v datech:
- Buzzati: The Tartar Steppe
- Cohen: Belle du Seigneur
- Sagan: Bonjour Tristesse
- Pratt: The Ballad of the Salty Sea






Jiný název:
- Gracq: The Opposing Shore /  Pobřeží Sy
- Clézio: The Interrogation /  Zápis o katas
   Miller: The Rosy Crucifixiontrofěrt

In [8]:
df.filter(pl.col("100_a").str.contains("Char, René"))

shape: (2, 73)
┌──────────┬─────────────┬───────────────┬───────────┬───┬───────────┬──────┬───────┬───────────┐
│ 100_ind1 ┆ 100_a       ┆ 100_7         ┆ 100_4     ┆ … ┆ 700_g     ┆ rok  ┆ stran ┆ vazba     │
│ ---      ┆ ---         ┆ ---           ┆ ---       ┆   ┆ ---       ┆ ---  ┆ ---   ┆ ---       │
│ str      ┆ str         ┆ str           ┆ list[str] ┆   ┆ list[str] ┆ i64  ┆ i64   ┆ str       │
╞══════════╪═════════════╪═══════════════╪═══════════╪═══╪═══════════╪══════╪═══════╪═══════════╡
│ 1        ┆ Char, René, ┆ jn20000603097 ┆ ["aut"]   ┆ … ┆ null      ┆ 1999 ┆ 108   ┆ null      │
│ 1        ┆ Char, René, ┆ jn20000603097 ┆ ["aut"]   ┆ … ┆ null      ┆ 1985 ┆ 304   ┆ brožovaná │
└──────────┴─────────────┴───────────────┴───────────┴───┴───────────┴──────┴───────┴───────────┘

In [9]:
df.filter(pl.col("100_a") == "Colette,")

shape: (25, 73)
┌──────────┬──────────┬───────────────┬───────────┬───┬───────────┬──────┬───────┬───────────┐
│ 100_ind1 ┆ 100_a    ┆ 100_7         ┆ 100_4     ┆ … ┆ 700_g     ┆ rok  ┆ stran ┆ vazba     │
│ ---      ┆ ---      ┆ ---           ┆ ---       ┆   ┆ ---       ┆ ---  ┆ ---   ┆ ---       │
│ str      ┆ str      ┆ str           ┆ list[str] ┆   ┆ list[str] ┆ i64  ┆ i64   ┆ str       │
╞══════════╪══════════╪═══════════════╪═══════════╪═══╪═══════════╪══════╪═══════╪═══════════╡
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1978 ┆ 233   ┆ pevná     │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1992 ┆ 231   ┆ brožovaná │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1913 ┆ 84    ┆ null      │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["lbt"]   ┆ … ┆ null      ┆ 1927 ┆ 33    ┆ brožovaná │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1935 ┆ 220   ┆ pevná     │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1935 ┆ 231   ┆ pevná     │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1935 ┆ 237   ┆ pevná     │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1931 ┆ 174   ┆ pevná     │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1931 ┆ 180   ┆ brožovaná │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1926 ┆ 156   ┆ null      │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1931 ┆ 126   ┆ pevná     │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1935 ┆ 286   ┆ pevná     │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1931 ┆ 192   ┆ null      │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1932 ┆ 170   ┆ brožovaná │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1934 ┆ 153   ┆ brožovaná │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1930 ┆ 209   ┆ pevná     │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1933 ┆ 193   ┆ pevná     │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1936 ┆ 164   ┆ null      │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1976 ┆ 118   ┆ pevná     │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1930 ┆ 153   ┆ brožovaná │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1961 ┆ 142   ┆ null      │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1932 ┆ 182   ┆ null      │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1931 ┆ 242   ┆ brožovaná │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1973 ┆ 264   ┆ null      │
│ 0        ┆ Colette, ┆ jn19981000507 ┆ ["aut"]   ┆ … ┆ null      ┆ 1993 ┆ 156   ┆ brožovaná │
└──────────┴──────────┴───────────────┴───────────┴───┴───────────┴──────┴───────┴───────────┘

## Bokklubben World Library

In [11]:
r = requests.get("https://en.wikipedia.org/wiki/Bokklubben_World_Library")
soup = BeautifulSoup(r.text)
tabulka_bokklubben = soup.find(class_="sortable")

In [12]:
len(tabulka_bokklubben.find_all("tr"))

101

In [13]:
for radek in tabulka_bokklubben.find_all("tr"):
    try:
        autor = radek.find_all("td")[1].text.strip().split(' ')[-1]
        print(f"{autor}: {radek.find_all("td")[0].text.strip()}")
        print(', '.join(set(df.filter(pl.col('100_a').str.contains(autor)).select(pl.col('245_a')).to_series().to_list())))
        print('***')
    except:
        pass

Achebe: Things Fall Apart
Svět se rozpadá, Muž z lidu, Už nikdy klid
***
Andersen: Fairy Tales
Povídka o roce, Spiknutí lásky, Najděte své ideální zdraví!, Slavík, George a Laura, Cínový vojáček, Mýty a legendy Polynésanů, Sněhová královna a jiné pohádky, Zpráva o cestě do Saského Švýcarska, Improvisator, Dvě baronky, Nové báchorky, Štěstí, Nejznámější pohádky Hanse Christiana Andersena, Analýza kořenových příčin, Hloupý Honza, Ten muž má něco do sebe, Pelle Dobyvatel, Čarovné zjevy, Pohádky Hanse Christiana Andersena, Ošklivé kachně, Balíček v ruksaku, Pastýřka a kominíček, J.C. Andersena vybrané pohádky, povídky a báchorky pro mládež a přátele její, Ošklivé kačátko, Slepí pasažéři, Ve spárech oceánu, Pět pohádek, Jane Fondová, Zámek u jezera, Císařovy nové šaty, Ztracená generace, Sněhová královna, Andersenovy báchorky, Šťastný Per, Andersenovy pohádky, Tajemství lásky, Jackie po Jackovi, Švéd loterista a jiné povídky, O princezně na hrášku a jiné pohádky, Kočky útočí, Divoké labutě, Křišťálové vidiny, Měsíček, Křesadlo a jiné pohádky, Starý dům a jiné pohádky, O dívce, která šlápla na chléb, Tlusťoch Olsen aj., Vybrané báchorky, Malý a velký Kalouš, Princezna na hrášku, Pohádky H. Ch. Andersena, Hans Christian Andersen: Nejkrásnější pohádky, Při nejzazším moři, Nehezké káče a jiné povídky, Pohádky, Válka o pekelný trůn, Vybrané Andersenovy pohádky, Mick Jagger, Pohádka mého života, Vzpomínky, Jack a Jackie Kennedyovi, Červené pantoflíčky, LEGO, Rudý Morten, Malenka, O princezně na hrášku, V železné době, Máš modrou krev, Nesnadné rozhodnutí, Flétnové hodiny, Vlček trosečníkem, Ďábel loterie, Úplný soubor jeho pohádek a povídek, Svatební šaty byly již objednány, Křesadlo, Nejlepší pohádky a povídky, Katharine Hepburnová & Spencer Tracy, Má velká doba byla malá, Milovat se zakazuje, Komtesa na scestí, Pohádky a povídky, H. Ch. Andersen, úplný soubor jeho pohádek a povídek, Výhra, Grimmové, Mimoňka, Pobřeží dětství, Kreslené pohádky, Dvanáct poštou, Rodina Frankova, Čarovná truhlice a jiné pohádky, Sviňáček a jiné pohádky, Pelle dobyvatel, Vlček a nejlepší kamarád, Dospělost je dar!, Rukojmí ISIS, Pasáček vepřů, Tajný život v Bílém domě, Muži už jsou takoví, Mořská žínka, Ošklivé káčátko, Nauč mne věřit ve štěstí, Buřič Morten, Den, kdy zemřela Diana, Po tisíciletích, Barbra, Hrášková princezna, H.C. Andersena Povídky a báchorky, Nejkrásnější pohádky H. Ch. Andersena, Osudná závěť, Císařův slavík, Ilustrované pohádky, Povídky a pohádky, Malá mořská víla, Andersenovy Vybrané báchorky, Nejkrásnější pohádky, Tesáky, Obrázková kniha bez obrázků, Volám tě zpátky, Dospělost je mýtus, U2, Dvojí život Sandry Sternové, William, Kate a malý George, Výbor veškerých povídek a báchorek H.C. Andersena, Dusty, Elizabeth Taylorová, Ditta, dcera člověka, Palečka a jiné pohádky, Ubulená hromádka štěstí
***
Alighieri: Divine Comedy
O jediné vládě, Nový život, To sladké jméno Beatrice, Ugolino, Peklo, Básně lyrické, Básnická díla, Božská komedie
***
Unknown: Epic of Gilgamesh

***
Unknown: Book of Job

***
Various: One Thousand and One Nights

***
fróði: Njál's Saga

***
Austen: Pride and Prejudice
Opatství Northhanger sic, Hledání štěstí, Lady Susan, Zraněný pastýř, Papež reformátor, Jane Austen - chawtonské dopisy, Úskalí lásky, Rozum a cit, Ema, Rozum a cit a mořské příšery, Pýcha a předsudek, Moudrost a vtip Jane Austenové, Opatství Northanger, Emma, Láska a přátelství, Watsonovi, Mansfieldské panství, Elinor a Marianna, Pýcha a přemlouvání, Romance u moře, Sanditon, Northangerské opatství, Anna Elliotová, Mladší sestra, Ztracené civilizace, Láska a přátelství a jiné prózy
***
Balzac: Le Père Goriot
Beatrice, Pirát Argow, Voršila Mirouëtová, Temná událost, Neznámé arcidílo, Sarrasine, Balzac a Stendhal o realismu, Lichvář Gobseck, Honorina, Ludvík Lambert, Šuani, Stará panna, Vytrvalá láska, Šprýmovné povídačky, kteréžto v opatstvech tourrainských nashromáždil a na světlo vydal pan de Balzac k obveselení pantagruelistův a žádných jiných, Sestřenice Běta, Gobseck, Šprýmovné povídky, sebrané v opatství Tourainském a vydané na světlo boží pánem de Balzac k obveselení pantagruelistů a žádných jiných, Modesta Mignonová, Rebelové, Otec Goriot, Okresní musa, Kabinet starožitností, Láska Tadeusze Paza, Lesk a bída kurtizán, Dcera Evina, Eugenie Grandetová, Krásná Imperia a jiné šprýmovné povídky, Poslanec, Výbor z díla II, Serafita, Kajícnice, Dům u pálkující kočky, Firma Nucingen a jiné novelly, Třicítiletá, Šuani, neboli, Bretaň roku 1799, Opuštěná žena, Albert Savarus, Neznámé veledílo, Bratranec Pons, Červená hospoda, Plawba Berezinská, Benátský žid, Umění platit své dluhy a uspokojit věřitele, aniž by bylo třeba vyjmout jediný halíř z vlastní kapsy, Farář tourský, Záhadný případ, Sbohem a jiné prózy, Venkované, Chouani, čili, Bretoňsko v roce 1799, Ztracené iluze, Vášeň na poušti, Flora Brazierová, Velikost a pád Césara Birotteaua, Teorie postele, Mládenecká domácnost, Psanci, Manželská smlouva, Drama na břehu mořském, Krevní msta, Žertovné povídky, Dvě povídky, Lesk a bída kurtisán, Farář Tourský a jiné povídky, Evženie Grandetová, Maskovaná milenka, Žena třicetiletá, Ďáblův dědic, El Verdugo, Ztracené iluse, Venkovský lékař, Lesk a bída kurtisan, Novely, Košilaté historky, Úvaha o elegantním životě, Chagrinová kůže, Vendetta, Zklamaná naděje, Tři povídky, Příběh o velikosti a pádu Césara Birotteaua, voňavkáře, náměstka starosty 2. okresu pařížského, rytíře řádu Čestné legie atd., Elixír života, Mercadet, O chuďasovi, jemuž říkávali Toulavá mošna, Hledání absolutna, Slovutný malíř, Neznámé veledílo a jiné prózy, Rozmarné povídky, Mše atheistova, Kajícnice a jiné povídky, Den, jenž nemá zítřka, Dopisy dvou mladých žen, Vévodkyně de Langeais 8, Plukovník Chabert, Tatík Goriot, Výbor z díla, Lilie v údolí, Modesta Mignonova, Ježíš Kristus ve Flandřích, Succubus, aneb, Běs sviňavý ženský, Šprýmovné povídky, kteréž po opatstvích tourainských sebral a na světlo boží jest vydal Pan de Balzac na povyražení pantagruelistův a nikoho jiného, Petřička, Všední hřích, Šagrénová kůže, Farář z Toursu, Fysiologie manželství, Modeste Mignonová, Historie velikosti a pádu Césara Birotteau-a, voňavkáře, rytíře řádu čestné legie, náměstka starosty 2. okrsku města Paříže, Studie ženy, Ztracené illuse, Vzpomínka na velkou revoluci, Fyziologie manželství, Umění platiti své dluhy a uspokojiti věřitele, aniž by bylo třeba vyjmouti jediný haléř z vlastní kapsy, Historie třinácti, Dívka se zlatýma očima, César Birotteau, Hodinky jeptišek z Poissy, Prokleté dítě, Spekulant, Třicetiletá, Stati a korespondence, Facino Cane, Oslí kůže, Eugénie Grandetová, Plukovník Chabert a jiné prózy, Milenka králova
***
Beckett: The Trilogy: Molloy, Malone Dies, The Unnamable
Jídlo, víno, přátelé, Novely a texty pro nic, Molloy, Katastrofa a jiná dramátka, Biologie, Poslední páska, O sýrech, Eseje, Toulky světem malířství, 1000 nejkrásnějších obrazů historie, Vaříme z vlastních zásob, Čekání na Godota, Evoluce, Chladný popel, Murphy, Malone umírá, Nepojmenovatelný, Tso, Konec hry, První láska, Chemie smrti, Texty pro nic
***
Boccaccio: The Decameron
Tři roztomilé novely mnoho pomlouvaného Giovanni Boccaccia, Dekameron, kterýž naps. messer Giovanni Boccaccio a z vlaštiny přel. Arnošt Procházka a dr. A. Pokorný, Malý Dekameron 3, aneb, Šťastné konce lásky, Fiesolské nymfy, Koš, aneb, Bludiště lásky, Malý Dekameron 1, aneb, Podoby lásky, Dekameron, kterýž napsal Giovanni Boccaccio, Malý Dekameron 2, aneb, Obratnosti lásky, Decameron, Rozprávka o jeptiškách, Život Dantův, Fiametta, Dekamerone, Vybrané povídky Giov. Boccaccia, Kratochvilné historie, Galantní historky, Griselda, Malý Dekameron 5, aneb, Věci lásky, Malý Dekameron 4, aneb, Taškařice lásky, Vybrané povídky, Dekameron, Nejstarší životopisy Dantovy
***
Borges: Ficciones
Obecné dějiny hanebnosti, Rubé, Artefakty, Zrcadla jsou zvláštní věc, Se psem je psina, Evaristo Carriego, Fikce, Fantastická zoologie, Další pátrání, Předmluvy s předmluvou předmluv, Zrcadlo a maska, Nesmrtelnost, Tvůrce, Ars poetica, Zvony... a kutny, Brodiova zpráva, Autobiografie
***
Brontë: Wuthering Heights
Sirotek lowoodský, Profesor, Jane Eyre, sirotek Lowoodský, Johana Eyre-ová, aneb, Sirotek lowoodský, Jane Eyreová, Bouřlivé výšiny, Shirley, Z letopisů Angrie, Johanna Eyre-ová, aneb Sirotek lowoodský, Sirotek Lowoodský, Na Větrné hůrce, Démon, Villette, Fika & hygge, Hana Eyrová, Vichrné návrší, Agnes Greyová, Dvojí život Heleny Grahamové, Jana Eyrová
***
Camus: The Stranger
Nedorozumění, Exil a království, Vyprávění severoamerických indiánů, Eseje, Svět Židů, Léto, Romány a povídky, Člověk revoltující, Spravedliví, Caligula, Cizinec, Pád, Zápisníky II, První člověk, Mor, Velká výměna, Zápisníky III, Zápisníky I, Král Roman, Mýtus o Sisyfovi, Šťastná smrt
***
Celan: Poems
Černé vločky, Sněžný part, Všechno je jinak, Báseň - domov v bezdomoví Paula Celana, Mříž hovorny, Růže nikoho
***
Céline: Journey to the End of the Night
Od zámku k zámku, Montessori pedagogika na doma, Skočná, Cesta na konec noci, Klaun's band II, Cesta do hlubin noci, Církev, Sever, Dítě a přírodní zákony, Škola mrtvol, Neexistující muzeum, Emma ve světě fantazie, Féerie pro jindy, Klaun's band I, Smrt na úvěr, Cena za dokonalost, Kincugi
***
Cervantes: Don Quixote
Persiles a Sigismunda, Cesta na Parnas, Poučné povídky, Bláznivý rytíř, Cikánečka, Tři Příkladné novely, Rytíř smutné postavy, O žárlivém Estremadurci, Vždycky není navěky, Cervantesovy novely, Numancie, Příkladné novely, Důmyslný rytíř Don Quijote de la Mancha, Tři komedie, Důmyslný rytíř don Quijote de la Mancha, Cervantesowy Nowely, O nerozvážném zvědavci, Pět meziher, Don Quijote de la Mancha, Coco, Duchaplný rytíř Don Quijote de la Mancha, Paní Cornelia, Jeskyně u Salamanky, Rohánek a Stříhálek, Zázračné divadlo, Don Quixote z la Manchy, Lišák Pedro, Don Quijote
***
Chaucer: The Canterbury Tales
Sen o rytíři, Troilus a Kriseida, Canterburské povídky, Povídky z pouti do Canterbury, Ptačí sněm, Výbor z Canterburských povídek Geofreye Chaucera
***
Chekhov: Stories

***
Conrad: Nostromo
Tajfun a jiné povídky, Svatba mnichova, Oheň pod palubou, Povídky z tropů, Souboj, Hříšné přání, Únik, O červených a černých, Pro Omaso není záchrany, Dohráno, Král a světec, Analýza podnikání s programem Microsoft Excel, Proroctví a dějiny světové, Asertivita, L.A. Candy, Hranice stínu, Nostromo, Gaspar Ruiz a jiné povídky, Limuzína, Peckova horda, Pokušení Peskarovo, Tajný agent, Jak věci fungují, Jíra Jenač, Deník z Konga, Zrcadlo moře, Mnichova svatba, Boží neklamné, prorocké hodiny světové, Rozuzlení, Memorix, Souvislosti, Almeyerův blud, Pirát, Lord Jim, Mezi přílivem a odlivem, Věrný Nostromo, Pokušení Pescarovo, Snadné háčkování, Černoch z lodi Narcissus, Zrození Venuše, Očima západu, Vítězství, Ku předu, Španělsko! ..., Poznámky o životě a literatuře, Malé sladké lži, Pobožnůstkář, Mezi mořem a pevninou, Zlatý šíp, Sexuální inteligence, Elektrohydraulické řídící systémy, Hitlerův pianista, Historické novelly o pruském králi Friedrichovi II. a jeho době, Hořkosladký život, Neklidné příběhy, Lodě, Elektrotechnika středem zájmu, Základna guerillových bojovníků, Nebe v mé duši, Černý námořník, Microsoft office Word 7.0, Excel 7.0, Tajemný vysílač, Tvá blízkost je mé štěstí, Kdo je pachatel?, Srdce temnoty, Vzdělávejte se!, Deset argumentů pro celibát, Znamení času konce, Schovej mě v náručí, Před očima západu, Vyhnanec z ostrovů, Almayerův vzdušný zámek, Páže Gustava Adolfa, Náhoda, Mezi zemí a mořem, Záchrana, Počátky, Pokrok, Moravská kuřátka, O nepřátelích říše, Bezbranná vášeň, Neznámá, Karibským mořem na lodi snů, Bestie a jiné čtyři povídky, Znamení času, Konopí pro zdraví, Výstřel z kazatelny, Laguna a jiné povídky o nepokoji, Malá cesta Terezie z Lisieux, 50 zlatých pravidel ofenzívního marketingu, MS Office 95, Guerilla marketing, Velcí inženýři
***
Dickens: Great Expectations
Americké poznámky, Cvrček u krbu, Pustý dům, Barnabáš Rudge, Dombey a syn, Dvě povídky, Povídka o malé Nelly, Klub Pickwicků, Ponurý dům, Vánoční povídky, Pár nohou, Děd a vnuk, Nikudy ven!, Evangelium podle Dickense, Veliké naděje, Pravda o případu D., Strašidelný dům a jeho příběhy, Záhada Edwina Drooda, David Copperfield, Tři vánoční povídky, Kruté časy, Život s dobrým koncem, První vítězství, Vánoční příběhy, Nadějné vyhlídky, Zvony novoroční, Večerní stíny, Starožitníkův krám, Dickensovo čtení, Život a příhody Mikuláše Nicklebyho, Otec a syn, Strašidelný dům, Kouzelná rybí kostička, Vánoční koleda, Zwony, Klub Pickwickův, Vánoční koleda prózou, Mikuláš Nickleby, Malá Dorritka, Kronika Pickwickova klubu, Cvrček na krbu, Příběh dvou měst, Pickwickovci, Krám starožitníkův, Štědrý večer, Příběh Davida Copperfielda, Zvony, Příhody Olivera Twista, Zlé časy, Život našeho Pána, Velké naděje, Črty, Čarovná rybí kostička, Dvě vánoční povídky, Oliver Twist, Koleda, Život a osudy Davida Copperfielda, Štedrý wečer, Vánoční koleda, čili, Vánoční povídka s duchy, Pan Pickwick, The Story of Richard Doubledick, Život a dobrodružství Martina Chuzzlewita, Román dvou měst, Výlet parníkem, Oliver Twist, aneb, Mladictwj sirotka, Volné radikály
***
Diderot: Jacques the Fatalist
Synovec Rameauův, Upovídané šperky, Myšlenky o křesťanském dogmatě, Výbor z díla, Malé romány a povídky, Je dobrý? Je zlý?, Jeptiška, Dva rozhovory, Rameauův synovec, Prospekt Encyklopedie, Jakub fatalista, Řeholnice, Jakub fatalista a jeho pán, Diderot o divadle, Vybrané spisy, O umění, Setkání s filozofem, Herecký paradox
***
Döblin: Berlin Alexanderplatz
Berlín, Alexandrovo náměstí, Amazonka, Milost se neuděluje, Valdštejn, Země, kde se neumírá
***
Dostoevsky: Crime and Punishment

***
Dostoevsky: The Idiot

***
Dostoevsky: Demons

***
Dostoevsky: The Brothers Karamazov

***
Eliot: Middlemarch
Jsme Bellingcat, O básnictví a básnících, Zpustlá země, Hudba na nebeském hradě, Jack Nicholson, Nesmrtelní ochránci, Vražda v katedrále, Cary Grant, Naučte se fotografovat ženy: 1000 dokonalých póz, Osud je černý jezdec, Červený mlýn, Pustina a jiné básně, Křesťan - kritik - básník, Ripuj, mixuj, vypaluj CD!, Pustá země, Romola, Hotel v noci, Čtyři kvartety, Americký rebel, Hon na krále démonů, Milostný příběh faráře Gilfila, Rodinné shromáždění, Middlemarch, Vojenské neúspěchy, Obnoviti křesťanství?, Silas Marner, tkadlec z Raveloe, Michael Douglas, Adam Bede, Paul Simon, Nádherní duchové, Stíny džungle, Praktická příručka o kočkách, Silas Marner, Vzestup a pád, Naučte se fotografovat kreativně
***
Ellison: Invisible Man
Drobný poklesek, V kleci, Pohřbeni, Neviditelný, Nemám ústa & musím křičet, Až na kost, Tajemství krve, Vrchol vulkánu, 365 způsobů, jak vychovat sebejisté dítě, Krásná pokojská, 365 tvůrčích her pro děti, Nebezpečné vize
***
Euripides: Medea

***
Faulkner: Absalom, Absalom!
Válečné lodě, Paní na Greystonu, Adobe Photoshop, Zápas lásky, Medvěd, Komáři, Adobe Photoshop CC, Prapory v prachu, Báj, Elly, Pobertové, Strom přání, Mink, Vesnice, Adobe Photoshop CS2, Divoké palmy, Panské sídlo, Hluk a vřava, Ostatní matky, Nepřemožení, Greenwich Park, Neodpočívej v pokoji, Svatyně, Absolone, Absolone!, Když jsem umírala, Město, Rekviem za jeptišku, Růže pro Emilii, Srpnové světlo
***
Faulkner: The Sound and the Fury
Válečné lodě, Paní na Greystonu, Adobe Photoshop, Zápas lásky, Medvěd, Komáři, Adobe Photoshop CC, Prapory v prachu, Báj, Elly, Pobertové, Strom přání, Mink, Vesnice, Adobe Photoshop CS2, Divoké palmy, Panské sídlo, Hluk a vřava, Ostatní matky, Nepřemožení, Greenwich Park, Neodpočívej v pokoji, Svatyně, Absolone, Absolone!, Když jsem umírala, Město, Rekviem za jeptišku, Růže pro Emilii, Srpnové světlo
***
Flaubert: Madame Bovary
Na pensi, Výchova sentimentální, Paměti bláznovy, Bibliomanie, Pokušení svatého Antonína, Korespondence, Přeludy života, Legenda o svatém Juliánovi Pohostinném, Salambo, Paní Bovaryová, Byli jednou dva písaři, Listopad, Bouvard a Pécuchet, Prosté srdce, Slovník přejatých myšlenek, Povídky Gustava Flauberta, Listy lásky, Legenda o svatém Julianu Hostiteli, Legenda o sv. Juliánu Pohostinném, Dílo je vše, Tři povídky, Dopisy, Mladého Flauberta Zápisky z cest, Citová výchova, Výbor z korespondence Gustava Flauberta, Herodias, Smarh, Výchova srdcem, Rozhovory o umění, bohu, životě a lidstvu, Salammbo, Cestovní deníky, Tanec mrtvých, Kandidát, Legenda o svatém Juliánovi pohostinném, Přeludy a život, Krajem a pobřežím, Julien, Pokušení sv. Antonína
***
Flaubert: Sentimental Education
Na pensi, Výchova sentimentální, Paměti bláznovy, Bibliomanie, Pokušení svatého Antonína, Korespondence, Přeludy života, Legenda o svatém Juliánovi Pohostinném, Salambo, Paní Bovaryová, Byli jednou dva písaři, Listopad, Bouvard a Pécuchet, Prosté srdce, Slovník přejatých myšlenek, Povídky Gustava Flauberta, Listy lásky, Legenda o svatém Julianu Hostiteli, Legenda o sv. Juliánu Pohostinném, Dílo je vše, Tři povídky, Dopisy, Mladého Flauberta Zápisky z cest, Citová výchova, Výbor z korespondence Gustava Flauberta, Herodias, Smarh, Výchova srdcem, Rozhovory o umění, bohu, životě a lidstvu, Salammbo, Cestovní deníky, Tanec mrtvých, Kandidát, Legenda o svatém Juliánovi pohostinném, Přeludy a život, Krajem a pobřežím, Julien, Pokušení sv. Antonína
***
Lorca: Gypsy Ballads
Básník v Novém Yorku, Dramata, Krvavá svatba, Úžasná ševcová, Fantastická ševcová, Uzavřený ráj, Pláňka, Balada na rynečku, Mariana Pinedová, Yerma, Eseje, Dům doni Bernardy, Písně na andaluskou notu, Básně F.G. Lorcy, Rozběhla se Carmen v tanci, V zahradě jsou s láskou svou Don Perlimplin s Belisou, Dům Bernardy Alby, Zelený vítr, Čarokrásná ševcová, Krev noci, Sonety temné lásky, A v Kordobě umírat..., A v Kordobě umírat ..., Cikánské romance, Svobodná paní Rosita, aneb, Květomluva, Neprovdaná paní Rosita, neboli, Mluva květů, Hry a hříčky, Dramata a próza, Lyrika, Dům Bernardy Albové
***
Márquez: One Hundred Years of Solitude
Dvanáct povídek o poutnících, Zpráva o jednom únosu, Neuvěřitelný a tklivý příběh o bezelstné Eréndiře a její ukrutné babičce, Sto roků samoty, Plukovníkovi nemá kdo psát, Generál ve svém labyrintu, Chile očima skryté kamery, Láska za časů cholery, Všechna špína světa, Devadesát dnů za železnou oponou, O lásce a jiných běsech, Zlá hodina, Dobrodružství Miguela Littína v Chile, Zpověď trosečníka, Kronika ohlášené smrti, Pohřeb Velké matky, Žít, abych mohl vyprávět, V tomhle městečku se nekrade, Uvidíme se v srpnu, Podzim patriarchy, Na paměť mým smutným courám, Oči modrého psa
***
Márquez: Love in the Time of Cholera
Dvanáct povídek o poutnících, Zpráva o jednom únosu, Neuvěřitelný a tklivý příběh o bezelstné Eréndiře a její ukrutné babičce, Sto roků samoty, Plukovníkovi nemá kdo psát, Generál ve svém labyrintu, Chile očima skryté kamery, Láska za časů cholery, Všechna špína světa, Devadesát dnů za železnou oponou, O lásce a jiných běsech, Zlá hodina, Dobrodružství Miguela Littína v Chile, Zpověď trosečníka, Kronika ohlášené smrti, Pohřeb Velké matky, Žít, abych mohl vyprávět, V tomhle městečku se nekrade, Uvidíme se v srpnu, Podzim patriarchy, Na paměť mým smutným courám, Oči modrého psa
***
Goethe: Faust

In [14]:
df.filter(pl.col("245_a").str.contains("Mahá")).select(pl.col("245_a")).to_series().to_list()

['Mahámudra',
 'Mahárádžův miláček',
 'Zlatý avatár Šrí Čaitanja Maháprabhu',
 'Mahájánový buddhismus',
 'Mahátma Gándhí',
 'Mahátma Gándhí',
 'Mahábhárata',
 'Život a učení Ramany Mahárišiho',
 'Mahárádžova nevěsta',
 'Tak pravil Ramana Maháriši',
 'Bhagavan Šrí Ramana Maháriši, mudrc z Arunáčaly',
 'Mahábhárata, aneb, Velký boj',
 '15 dní s Mahátma Gándhím',
 'Mahábhárata, aneb, Velký boj',
 'Mahátmá Gándhí',
 'Ježíš Kristus a Ramana Maháriši',
 'Mahámudrá',
 'Světlo Asie, čili, Veliké odříkání (Mahábhiniškramana), to jest život a učení Gótamy, prince indického a zakladatele buddhismu (jak vyprávěno ve verších indickým buddhistou)',
 'S Ramanou Mahárišim den za dnem',
 'Mahájánské texty',
 'Mahábhárata',
 'Zamyšlení nad výroky Ramana Mahárišiho všeobecně a v knize "The conscious immortality - Vědomá nesmrtelnost" zvláště',
 'Mahárádžův miláček',
 'Mahátma Gándhí',
 'Mahátmá Gándhí',
 'Světlo na učení Bhagavána Šrí Ramana Maháršiho',
 'Mahátma Gándhí',
 'Bhagavan Šrí Ramana Maháriši, mudrc z Arunáčaly',
 'Mahárišiho evangelium',
 'Mahábhárata I',
 'Rozhovory s Ramanou Mahárišim']

In [15]:
df.filter(pl.col("245_a").str.contains("Sága")).select(pl.col("245_a")).to_series().to_list()

['Sága Prokletých',
 'Sága',
 'Sága zapomenutého válečníka',
 'Sága rodu Chlebakupova',
 'Sága rodu Koželuhů',
 'Sága rodu Masaryků',
 'Sága Prokletých',
 'Sága rodu kulometů',
 'Sága rodu Hardacrů',
 'Sága o Hákonovi',
 'Sága o životě a smrti Jana Bati a jeho bratra Tomáše',
 'Sága rodu Benešů',
 'Sága temných templářů',
 'Sága našeho rodu',
 'Sága rodu Forsytů',
 'Sága od Bodamského jezera',
 'Sága rodu Chlebakupova',
 'Sága o cestě na Island',
 'Sága Valty',
 'Sága',
 'Sága rodiny Škodů',
 'Sága českého lékaře po 92 letech',
 'Sága temných templářů',
 'Sága o životě a smrti Jana Bati a jeho bratra Tomáše',
 'Sága o Volsunzích',
 'Sága Sirionů',
 'Sága rodu Forsytů',
 'Sága našeho rodu',
 'Sága rodu Chabalů',
 'Sága od Bodamského jezera',
 'Sága rodu Budilova',
 'Sága rodu Forsytů',
 'Sága',
 'Sága Světoborci',
 'Sága o Salavinovi',
 'Sága rodu Forsytů',
 'Sága rodu Reissových',
 'Sága Sirionů',
 'Sága rodu Habsburků',
 'Sága rodu Budilova',
 'Sága Zelených kostí',
 'Super Spellsword Sága',
 'Sága',
 'Sága stmívání',
 'Sága rodu Kinských',
 'Sága rodu chirurgů',
 'Sága od Bodamského jezera',
 'Sága Sirionů',
 'Sága našeho rodu',
 'Sága rodu Forsytů',
 'Sága o Lundirovi - synu zimy, hvězdopravci a staviteli',
 'Sága jihu',
 'Sága 2. světové války',
 'Sága rodu Forsytů',
 'Sága pušek, seker a las',
 'Sága rodu křídloprachů',
 'Sága o Wannovi, synu Orlygově',
 'Sága krále Laurina',
 'Sága rodu',
 'Sága Stmívání: oficiální ilustrovaný průvodce',
 'Sága rodu Rotwengelů',
 'Sága zapomenutého válečníka',
 'Sága Lartena Hroozleyho',
 'Sága Lartena Hroozleyho',
 'Sága rodu Forsytů',
 'Sága našich dnů',
 'Sága Sirionů',
 'Sága rodu Marxů',
 'Sága z Valhally',
 'Sága rodu Mühligů',
 'Sága rodu Floriů',
 'Sága Sirionů',
 'Sága rodu Forsytů',
 'Sága rodu Forsytů',
 'Sága o Narviku',
 'Sága rodu Forsytů',
 'Sága zapomenutého válečníka',
 'Sága pana Janíčka',
 'Sága rodu Forsytů',
 'Sága rodu Forsytů',
 'Sága Lartena Hroozleyho',
 'Sága rodu Forsytů',
 'Sága o Salavinovi',
 'Sága rodu Forsytů',
 'Sága Sirionů',
 'Edda a Sága o Ynglinzích',
 'Sága rodu Forsytů',
 'Sága o svatém Olavu',
 'Sága o životě a smrti Jana Bati a jeho bratra Tomáše',
 'Sága o Hákonovi',
 'Sága Prokletých',
 'Sága rodu',
 'Sága rodu Forsytů',
 'Sága o letu a ohni',
 'Sága rodu Porsche',
 'Sága černého zlata pod Brdy',
 'Sága rodu Chlebakupova',
 'Sága o Halldorovi z Mortaluny',
 'Sága o Hervaře',
 'Sága o životě a smrti Jana Bati a jeho bratra Tomáše',
 'Sága Sirionů',
 'Sága rodu Forsytů',
 'Sága Sirionů',
 'Sága Prokletých',
 'Sága temných templářů',
 'Sága o Hákonovi',
 'Sága o svatém Óláfovi',
 'Sága rodu Floriů',
 'Sága rodu Forsytů',
 'Sága rodu Floriů',
 'Sága Lartena Hroozleyho']

Nevyšlo:
- Celan: Poems
- Rosa: The Devil to Pay in the Backlands
- Lessing: The Golden Notebook
- Salih: Season of Migration to the North

spíš vyšlo:
- Rumi: Masnavi
- fróði: Njál's Saga

In [17]:
df.filter(pl.col("100_a").str.contains("Celan, Paul"))

shape: (6, 73)
┌──────────┬──────────────┬───────────────┬───────────┬───┬───────────┬──────┬───────┬───────────┐
│ 100_ind1 ┆ 100_a        ┆ 100_7         ┆ 100_4     ┆ … ┆ 700_g     ┆ rok  ┆ stran ┆ vazba     │
│ ---      ┆ ---          ┆ ---           ┆ ---       ┆   ┆ ---       ┆ ---  ┆ ---   ┆ ---       │
│ str      ┆ str          ┆ str           ┆ list[str] ┆   ┆ list[str] ┆ i64  ┆ i64   ┆ str       │
╞══════════╪══════════════╪═══════════════╪═══════════╪═══╪═══════════╪══════╪═══════╪═══════════╡
│ 1        ┆ Celan, Paul, ┆ jn20030827047 ┆ ["aut"]   ┆ … ┆ null      ┆ 2023 ┆ 169   ┆ brožovaná │
│ 1        ┆ Celan, Paul, ┆ jn20030827047 ┆ ["aut"]   ┆ … ┆ null      ┆ 2015 ┆ 206   ┆ brožovaná │
│ 1        ┆ Celan, Paul, ┆ jn20030827047 ┆ ["aut"]   ┆ … ┆ null      ┆ 2015 ┆ 377   ┆ null      │
│ 1        ┆ Celan, Paul, ┆ jn20030827047 ┆ ["aut"]   ┆ … ┆ null      ┆ 2012 ┆ 115   ┆ brožovaná │
│ 1        ┆ Celan, Paul, ┆ jn20030827047 ┆ ["aut"]   ┆ … ┆ null      ┆ 1986 ┆ 230   ┆ pevná     │
│ 1        ┆ Celan, Paul, ┆ jn20030827047 ┆ ["aut"]   ┆ … ┆ null      ┆ 2024 ┆ 275   ┆ pevná     │
└──────────┴──────────────┴───────────────┴───────────┴───┴───────────┴──────┴───────┴───────────┘

## The New York Times' 100 Best Books of the 21st Century

In [19]:
r = requests.get("https://en.wikipedia.org/wiki/The_New_York_Times%27_100_Best_Books_of_the_21st_Century")
soup = BeautifulSoup(r.text)
tabulka_21 = soup.find(class_="sortable")

In [20]:
lide = []
for radek in tabulka_21.find_all("tr"):
    if "20" in radek.text:
        autorstvo = radek.find_all("td")[2].text.split(' ')[-1]
        autorstvo_krestni = radek.find_all("td")[2].text.split(' ')[0]
        lide.append(f"{autorstvo_krestni}: {autorstvo}")
len(set(lide))

87

In [21]:
for radek in tabulka_21.find_all("tr"):
    if "20" in radek.text:
        titul = radek.find_all("td")[1].text
        autorstvo = radek.find_all("td")[2].text.split(' ')[-1]
        autorstvo_krestni = radek.find_all("td")[2].text.split(' ')[0]
        print(f"{radek.find_all('td')[2].text}: {titul}")
        print(', '.join(set(df.filter(pl.col('100_a').str.contains(autorstvo)).filter(pl.col('100_a').str.contains(autorstvo_krestni)).select(pl.col('245_a')).to_series().to_list())))
        print("***")

Elena Ferrante: My Brilliant Friend
Geniální přítelkyně, Příležitostné nápady, Tíživá láska, Na okraji, Prolhaný život dospělých, Dny opuštění, Pláž v noci, Temná dcera
***
Isabel Wilkerson: The Warmth of Other Suns

***
Hilary Mantel: Wolf Hall
Předveďte mrtvé, Zavraždění Margaret Thatcherové a jiné povídky, Wolf Hall, Za temnotou, Zrcadlo a světlo
***
Edward P. Jones: The Known World
Hotel Babylon, aneb, Nechcete raději zůstat doma?, Módní salon Babylon, aneb, Nechcete raději nakupovat konfekci?, Letiště Babylon, aneb, Nechcete raději jet vlakem?, Access 2000
***
Jonathan Franzen: The Corrections
Svoboda, Purity, Rozhřešení
***
Roberto Bolaño: 2666
Třetí říše, Chilské nokturno, Amulet, Divocí detektivové, Vzdálená hvězda, Nacistická literatura v Americe, 2666
***
Colson Whitehead: The Underground Railroad
Podzemní železnice, Zóna jedna
***
W.G. Sebald: Austerlitz

***
Kazuo Ishiguro: Never Let Me Go
Neutěšenci, Vybledlá krajina s kopci, Pohřbený obr, Neopouštěj mě, Nokturna, Soumrak dne, Klára a Slunce, Malíř pomíjivého světa, Když jsme byli sirotci
***
Marilynne Robinson: Gilead
Domov, Ztrácení, Lila, Gilead
***
Junot Díaz: The Brief Wondrous Life of Oscar Wao
Krátký, leč divuplný život Oskara Wajda, A v tu chvíli je po lásce
***
Joan Didion: The Year of Magical Thinking
Lízni si a hrej, Demokracie, Kniha denních modliteb, Víc než další den
***
Cormac McCarthy: The Road
Krvavý poledník, aneb, Večerní červánky na západě, Konzultant, Hranice, Vlak Sunset Limited, Strážce sadu, Stella Maris, Pasažér, Suttree, Tahle země není pro starý, Města na planině, Všichni krásní koně, Vnější tma, Dítě Boží, Cesta
***
Rachel Cusk: Outline
Obrys, Arlington Park
***
Min Jin Lee: Pachinko
Pačinko
***
Michael Chabon: The Amazing Adventures of Kavalier & Clay
Záhady Pittsburghu, Konečné řešení, Telegraph Avenue, Mapy & legendy, Zázrační hoši, Modelový svět, Úžasná dobrodružství Kavaliera a Claye, Měsíční svit, Židovský policejní klub
***
Paul Beatty: The Sellout
Zaprodanec
***
George Saunders: Lincoln in the Bardo
Lincoln v bardu, Desátého prosince, Památník války severu proti jihu v časech hlubokého úpadku
***
Patrick Radden Keefe: Say Nothing
Impérium bolesti
***
Percival Everett: Erasure
Jižanské stromy divné ovoce nesou
***
Matthew Desmond: Evicted

***
Katherine Boo: Behind the Beautiful Forevers
Krásné zítřky
***
Alice Munro: Hateship, Friendship, Courtship, Loveship, Marriage
Příliš mnoho štěstí, Útěk, Už dávno ti chci něco říct a jiné povídky, Láska dobré ženy, Nepřítel, přítel, ctitel, milenec, manžel, Veřejná tajemství, Přítelkyně z mládí, Drahý život
***
Richard Powers: The Overstory
Stromy znamenají svět, Stopy paměti
***
Adrian Nicole LeBlanc: Random Family

***
Ian McEwan: Atonement
Na Chesilské pláži, Amsterdam, Myslete na děti!, Sobota, Betonová zahrada, Solar, Psychopolis a jiné povídky, Hodiny, Nezničitelná láska, Dítě v pravý čas, Skořápka, Šváb, Nevinný, Černí psi, První láska, poslední pomazání, Mlsoun, Amsterodam, Pokání, Snílek, Stroje jako já a lidé jako vy, Cizinci ve městě
***
Chimamanda Ngozi Adichie: Americanah
Milá Ijeawele, aneb, Feministický manifest v patnácti doporučeních, Co ti svírá hrdlo, Amerikána, Zápisky o smutku, Půl žlutého slunce, Feminismus je pro každého, Purpurový ibišek
***
David Mitchell: Cloud Atlas
Dům za zdí, Tisíc podzimů Jacoba de Zoeta, Atlas mraků, Hodiny z kostí, Sencislo9, Utopia Avenue, aneb, Cesta do Tramtárie, Třináct měsíců, Hybatelé
***
Helen DeWitt: The Last Samurai
Poslední samuraj
***
Jesmyn Ward: Sing, Unburied, Sing
Píseň zbloudilých duší
***
Zadie Smith: White Teeth
O kráse, Bílé zuby, Sběratel autogramů, Severozápad
***
Alan Hollinghurst: The Line of Beauty
Sparsholtova aféra, Linie krásy, Cizí dítě
***
Jesmyn Ward: Salvage the Bones
Píseň zbloudilých duší
***
Claudia Rankine: Citizen

***
Alison Bechdel: Fun Home
Lesby k pohledání, Rodinný ústav
***
Ta-Nehisi Coates: Between the World and Me
Kdo tančí s vodou
***
Annie Ernaux: The Years
Místo, Paměť dívky, Mladík, Roky
***
Roberto Bolaño: The Savage Detectives
Třetí říše, Chilské nokturno, Amulet, Divocí detektivové, Vzdálená hvězda, Nacistická literatura v Americe, 2666
***
Jennifer Egan: A Visit From the Goon Squad
Hrad, Návštěva bandy rváčů
***
Helen Macdonald: H Is for Hawk
J jako jestřáb
***
Claire Keegan: Small Things Like These
Takové maličkosti, Třetí světlo, Modrá pole, Na konci dne
***
Marlon James: A Brief History of Seven Killings
Temná hvězda
***
Tony Judt: Postwar
Zle se vede zemi, Penzion vzpomínek, Falešné ideje, cizí krev, Intelektuál ve dvacátém století, Zapomenuté 20. století, Velká iluze?, Poválečná Evropa
***
N. K. Jemisin: The Fifth Season
Snová krev, Mass Effect, Stali jsme se městem, Sto tisíc království, Zlomená země
***
Maggie Nelson: The Argonauts

***
Donna Tartt: The Goldfinch
Stehlík, Malý kamarád, Tajná historie
***
Toni Morrison: A Mercy
Milosrdenství, Láska, Velmi modré oči, Milovaná, Šalomounova píseň, Nejmodřejší oči, Domov, Ráj, Jazz
***
Marjane Satrapi: Persepolis
Ajdar, Persepolis 2, Persepolis, Strašidla se bojí měsíce, Šitíčko, Kuře na švestkách
***
Han Kang: The Vegetarian
Bílá kniha, Kde kvete tráva, Neloučím se navždy, Vegetariánka
***
Hernan Diaz: Trust

***
Kate Atkinson: Life After Life
V zákulisí muzea, Chrámy veselí, Přepis, Život za životem, Kdy už přijdou dobré zprávy?, Něco za něco, Bůh v troskách, Neuzavřené případy
***
Denis Johnson: Train Dreams
Sloupové dýmu, Nikdo ani hnout!
***
Alice Munro: Runaway
Příliš mnoho štěstí, Útěk, Už dávno ti chci něco říct a jiné povídky, Láska dobré ženy, Nepřítel, přítel, ctitel, milenec, manžel, Veřejná tajemství, Přítelkyně z mládí, Drahý život
***
George Saunders: Tenth of December
Lincoln v bardu, Desátého prosince, Památník války severu proti jihu v časech hlubokého úpadku
***
Lawrence Wright: The Looming Tower
Víra ve víru, Na konci října
***
Rachel Kushner: The Flamethrowers
Noční klub Mars
***
Barbara Ehrenreich: Nickel and Dimed

***
Hua Hsu: Stay True
Pejsek, Na farmě, Králíček, Kuřátko, Na lodi, Jak to žije u mimozemšťanů, Mláďata z divočiny, V noci, Mláďata z farmy, Cesta autobusem, Krásné narozeniny, Ve městě, Kočička
***
Jeffrey Eugenides: Middlesex
Hra o manželství, Sebevraždy panen, Povídky z první ruky, Hermafrodit
***
Kiese Laymon: Heavy

***
Barbara Kingsolver: Demon Copperhead
Píseň jedovatého stromu, Lakuna
***
Ben Lerner: 10:04
Topecká škola
***
Mary Gaitskill: Veronica

***
Rebecca Makkai: The Great Believers

***
Philip Roth: The Plot Against America
Lidská skvrna, Hodina anatomie, Ňadro, Druhý život, Pokoření, Vzala jsem si komunistu, Milostné rozmluvy, Sabbathovo divadlo, Portnoyův komplex, Ať se děje, co se děje, Umírající zvíře, Klam, Spiknutí proti Americe, Zuckerman zbavený pout, Sbohem, město C, Duch odchází, Elév, Americká idyla, Pražské orgie, Sbohem, město C. a pět povídek, Jako každý člověk, Odkaz, Rozhořčení, Nemesis, Operace Shylock, Žít jako muž, Profesor touhy
***
Justin Torres: We the Animals
My, zvířata
***
Andrew Solomon: Far From the Tree

***
Sigrid Nunez: The Friend

***
Michelle Alexander: The New Jim Crow

***
Edward P. Jones: All Aunt Hagar's Children
Hotel Babylon, aneb, Nechcete raději zůstat doma?, Módní salon Babylon, aneb, Nechcete raději nakupovat konfekci?, Letiště Babylon, aneb, Nechcete raději jet vlakem?, Access 2000
***
Tove Ditlevsen: The Copenhagen Trilogy
Tváře, Kodaňská trilogie
***
Svetlana Alexievich: Secondhand Time

***
Robert Caro: The Passage of Power
Vysněná kavárna na zámku
***
Elizabeth Strout: Olive Kitteridge
Burgessovi chlapci, Olive Kitteridgeová je zpět, Jmenuji se Lucy Bartonová, Olive Kitteridgeová, Všechno je možné
***
Mohsin Hamid: Exit West
Jak nechutně zbohatnout v rozvojové Asii, Exit west
***
Gabrielle Zevin: Tomorrow, and Tomorrow, and Tomorrow
Zítra a zítra, zítra, zítra, zítra, Někde jinde, Příběhy opředený život A.J. Fikryho
***
Tayari Jones: An American Marriage
Jedno manželství
***
Jon Fosse: Septology
Jméno, Mámení, Na sklonku dne, To je Ales, Melancholie, Sny Olavovy, Ráno a večer
***
Lucia Berlin: A Manual for Cleaning Women
Manuál pro uklízečky
***
Elena Ferrante: The Story of the Lost Child
Geniální přítelkyně, Příležitostné nápady, Tíživá láska, Na okraji, Prolhaný život dospělých, Dny opuštění, Pláž v noci, Temná dcera
***
John Jeremiah Sullivan: Pulphead
Medvědí právo, Prezident, papež a premiérka, Diskuse o demokracii, Milostné aféry amerických prezidentů, Probuzený lev, Cesta od roku 1989, Prokletí euronacionalismu, Sbohem železné lady, Kterak nepřistupovat k imigraci
***
Fernanda Melchor: Hurricane Season
Období hurikánů
***
Benjamín Labatut: When We Cease to Understand the World
Maniac, Strašlivá závrať
***
Siddhartha Mukherjee: The Emperor of All Maladies
Gen, Vládkyně všech nemocí
***
George Saunders: Pastoralia
Lincoln v bardu, Desátého prosince, Památník války severu proti jihu v časech hlubokého úpadku
***
David W. Blight: Frederick Douglass

***
Torrey Peters: Detransition, Baby

***
Lydia Davis: The Collected Stories of Lydia Davis

***
Hisham Matar: The Return
V zemi mužů
***
Viet Thanh Nguyen: The Sympathizer
Sympatizant
***
Philip Roth: The Human Stain
Lidská skvrna, Hodina anatomie, Ňadro, Druhý život, Pokoření, Vzala jsem si komunistu, Milostné rozmluvy, Sabbathovo divadlo, Portnoyův komplex, Ať se děje, co se děje, Umírající zvíře, Klam, Spiknutí proti Americe, Zuckerman zbavený pout, Sbohem, město C, Duch odchází, Elév, Americká idyla, Pražské orgie, Sbohem, město C. a pět povídek, Jako každý člověk, Odkaz, Rozhořčení, Nemesis, Operace Shylock, Žít jako muž, Profesor touhy
***
Elena Ferrante: The Days of Abandonment
Geniální přítelkyně, Příležitostné nápady, Tíživá láska, Na okraji, Prolhaný život dospělých, Dny opuštění, Pláž v noci, Temná dcera
***
Emily St. John Mandel: Station Eleven
Skleněný hotel, Stanice 11, Moře klidu
***
Zadie Smith: On Beauty
O kráse, Bílé zuby, Sběratel autogramů, Severozápad
***
Hilary Mantel: Bring Up the Bodies
Předveďte mrtvé, Zavraždění Margaret Thatcherové a jiné povídky, Wolf Hall, Za temnotou, Zrcadlo a světlo
***
Saidiya Hartman: Wayward Lives, Beautiful Experiments

***
Jesmyn Ward: Men We Reaped
Píseň zbloudilých duší
***
Ann Patchett: Bel Canto
Holandská vila, Země divů, Společenství, Bel canto
***
Ali Smith: How to Be Both
Hotel svět, Jiné povídky a jiné povídky, Tam někde za duhou, Šití
***
Denis Johnson: Tree of Smoke
Sloupové dýmu, Nikdo ani hnout!
***

Nevyšlo:
- Isabel Wilkerson: The Warmth of Other Suns- Edward P. Jones: The Known World
- Patrick Radden Keefe: Say Nothing
- Richard Powers: The Overstory
- vůbec: - Matthew Desmond: Evicted
- vůbec: Claudia Rankine: Citizen
- Ta-Nehisi Coates: Between the World and Me
- Marlon James: A Brief History of Seven Killings
- N. K. Jemisin: The Fifth Season
- vůběc: Maggie Nelson: The Argonauts
- vůbec: Hernan Diaz: Trust
- Rachel Kushner: The Flamethrowers
- vůbec: Barbara Ehrenreich: Nickel and Dimed
- Hua Hsu: Stay True
- vůbec: Kiese Laymon: Heavy
- Barbara Kingsolver: Demon Copperhead
- Ben Lerner: 10:04- vůbec: Mary Gaitskill: Veronica- vůbec: Rebecca Makkai: The Great Believers
- vůbec: Andrew Solomon: Far From the Tree- vůbec: *
Sigrid Nunez: The Frie- vůbec: 
***
Michelle Alexander: The New Jim- Edward P. Jones: All Aunt Hagar's Children
- (asi vůbec) Robert Caro: The Passage of Power
- John Jeremiah Sullivan: Pulphead
- George Saunders: Pastoralia
- vůbec: David W. Blight: Frederick Douglass- vůbec: *
Torrey Peters: Detransition, Ba- vůbec: 
***
Lydia Davis: The Collected Stories of Lydia
- Hisham Matar: The Return
- Saidiya Hartman: Wayward Lives, Beautiful Experiments
- Jesmyn Ward: Men We Reaped Davis
 Crow



Težko ří
- Denis Johnson: Train Dreamsct:
- Percival Everett: Erasu- Lawrence Wright: The Looming Towerte
- Ian McEwan: Atonementd

In [23]:
df.filter(pl.col("100_a").str.contains("Rankine, Clau"))

shape: (0, 73)
┌──────────┬───────┬───────┬───────────┬───┬───────────┬─────┬───────┬───────┐
│ 100_ind1 ┆ 100_a ┆ 100_7 ┆ 100_4     ┆ … ┆ 700_g     ┆ rok ┆ stran ┆ vazba │
│ ---      ┆ ---   ┆ ---   ┆ ---       ┆   ┆ ---       ┆ --- ┆ ---   ┆ ---   │
│ str      ┆ str   ┆ str   ┆ list[str] ┆   ┆ list[str] ┆ i64 ┆ i64   ┆ str   │
╞══════════╪═══════╪═══════╪═══════════╪═══╪═══════════╪═════╪═══════╪═══════╡
└──────────┴───────┴───────┴───────────┴───┴───────────┴─────┴───────┴───────┘

## Cesta na sever

In [44]:
df.filter(pl.col("245_a").str.contains("Cesta na sever"))

shape: (32, 73)
┌──────────┬────────────────────────┬───────────────┬───────────────────────┬───┬───────────┬──────┬───────┬───────────┐
│ 100_ind1 ┆ 100_a                  ┆ 100_7         ┆ 100_4                 ┆ … ┆ 700_g     ┆ rok  ┆ stran ┆ vazba     │
│ ---      ┆ ---                    ┆ ---           ┆ ---                   ┆   ┆ ---       ┆ ---  ┆ ---   ┆ ---       │
│ str      ┆ str                    ┆ str           ┆ list[str]             ┆   ┆ list[str] ┆ i64  ┆ i64   ┆ str       │
╞══════════╪════════════════════════╪═══════════════╪═══════════════════════╪═══╪═══════════╪══════╪═══════╪═══════════╡
│ 1        ┆ Čapek, Karel,          ┆ jk01021023    ┆ ["aut", "ill"]        ┆ … ┆ null      ┆ 1948 ┆ 285   ┆ brožovaná │
│ 1        ┆ Čapek, Karel,          ┆ jk01021023    ┆ ["aut", "ill"]        ┆ … ┆ null      ┆ 1940 ┆ 285   ┆ pevná     │
│ 1        ┆ Čapek, Karel,          ┆ jk01021023    ┆ ["aut", "ill"]        ┆ … ┆ null      ┆ 1937 ┆ 285   ┆ null      │
│ 1        ┆ Čapek, Karel,          ┆ jk01021023    ┆ ["aut", "ill"]        ┆ … ┆ null      ┆ 1941 ┆ 285   ┆ brožovaná │
│ 1        ┆ Čapek, Karel,          ┆ jk01021023    ┆ ["aut"]               ┆ … ┆ null      ┆ 1939 ┆ 285   ┆ brožovaná │
│ 1        ┆ Procházka, Miroslav,   ┆ ola2002139630 ┆ ["aut"]               ┆ … ┆ null      ┆ 2009 ┆ 53    ┆ brožovaná │
│ 1        ┆ Čapek, Karel,          ┆ jk01021023    ┆ ["aut", "ill"]        ┆ … ┆ null      ┆ 2022 ┆ 294   ┆ pevná     │
│ 1        ┆ Čapek, Karel,          ┆ jk01021023    ┆ ["aut", "ill"]        ┆ … ┆ null      ┆ 1955 ┆ 275   ┆ null      │
│ 1        ┆ Mašín, Ctirad,         ┆ jn20000728402 ┆ ["aut"]               ┆ … ┆ null      ┆ 2024 ┆ 191   ┆ brožovaná │
│ 1        ┆ Mašín, Ctirad,         ┆ jn20000728402 ┆ ["aut"]               ┆ … ┆ null      ┆ 2010 ┆ 311   ┆ pevná     │
│ 1        ┆ Grimaldi, Virginie,    ┆ xx0215444     ┆ ["aut"]               ┆ … ┆ null      ┆ 2019 ┆ 277   ┆ brožovaná │
│ 1        ┆ Roberts, Kenneth       ┆ jn19990007077 ┆ ["aut"]               ┆ … ┆ null      ┆ 1948 ┆ 533   ┆ pevná     │
│          ┆ Lewis,                 ┆               ┆                       ┆   ┆           ┆      ┆       ┆           │
│ 1        ┆ Čapek, Karel,          ┆ jk01021023    ┆ ["aut", "ill"]        ┆ … ┆ null      ┆ 1939 ┆ 285   ┆ null      │
│ 1        ┆ Jordánová, Zdeňka,     ┆ xx0018362     ┆ ["aut"]               ┆ … ┆ null      ┆ 2019 ┆ 353   ┆ pevná     │
│ 1        ┆ Čapek, Karel,          ┆ jk01021023    ┆ ["aut", "ill"]        ┆ … ┆ null      ┆ 1937 ┆ 285   ┆ brožovaná │
│ 1        ┆ Čapek, Karel,          ┆ jk01021023    ┆ ["aut", "ill"]        ┆ … ┆ null      ┆ 1936 ┆ 285   ┆ pevná     │
│ 1        ┆ Roberts, Kenneth       ┆ jn19990007077 ┆ ["aut"]               ┆ … ┆ null      ┆ 1939 ┆ 502   ┆ pevná     │
│          ┆ Lewis,                 ┆               ┆                       ┆   ┆           ┆      ┆       ┆           │
│ 1        ┆ Čapek, Karel,          ┆ jk01021023    ┆ ["aut"]               ┆ … ┆ null      ┆ 1936 ┆ 285   ┆ null      │
│ 1        ┆ Drábek, Antonín,       ┆ jn20001005172 ┆ ["aut"]               ┆ … ┆ null      ┆ 2004 ┆ 175   ┆ brožovaná │
│ 1        ┆ Roberts, Kenneth       ┆ jn19990007077 ┆ ["aut"]               ┆ … ┆ null      ┆ 1977 ┆ 688   ┆ pevná     │
│          ┆ Lewis,                 ┆               ┆                       ┆   ┆           ┆      ┆       ┆           │
│ 1        ┆ Čapek, Karel,          ┆ jk01021023    ┆ ["aut", "ill"]        ┆ … ┆ null      ┆ 2000 ┆ 285   ┆ brožovaná │
│ 1        ┆ Hohlbein, Wolfgang,    ┆ jn20000602973 ┆ ["aut"]               ┆ … ┆ null      ┆ 1998 ┆ 207   ┆ pevná     │
│ 1        ┆ Čapek, Karel,          ┆ jk01021023    ┆ ["aut", "ill"]        ┆ … ┆ null      ┆ 1970 ┆ 291   ┆ pevná     │
│ 1        ┆ Roberts, Kenneth       ┆ jn19990007077 ┆ ["aut"]               ┆ … ┆ null      ┆ 1941 ┆ 502   ┆ null      │
│          ┆ Lewis,                 ┆               ┆                       ┆   ┆           ┆      ┆       ┆           │
│ 1        ┆ Roberts, Kenneth       ┆ jn19990007077 ┆ ["aut"]               ┆ … ┆ null      ┆ 1971 ┆ 598   ┆ null      │
│          ┆ Lewis,                 ┆               ┆                       ┆   ┆           ┆      ┆       ┆           │
│ 1        ┆ Roberts, Kenneth       ┆ jn19990007077 ┆ ["aut"]               ┆ … ┆ null      ┆ 1994 ┆ 706   ┆ pevná     │
│          ┆ Lewis,                 ┆               ┆                       ┆   ┆           ┆      ┆       ┆           │
│ 1        ┆ Čáka, Jan,             ┆ jk01020955    ┆ ["aut", "ill", "pht"] ┆ … ┆ null      ┆ 1971 ┆ 180   ┆ pevná     │
│ 1        ┆ Nagel, H. C.           ┆ jx20040915018 ┆ ["aut"]               ┆ … ┆ null      ┆ 1992 ┆ 62    ┆ brožovaná │
│ 1        ┆ Roberts, Kenneth       ┆ jn19990007077 ┆ ["aut"]               ┆ … ┆ null      ┆ 1940 ┆ 502   ┆ brožovaná │
│          ┆ Lewis,                 ┆               ┆                       ┆   ┆           ┆      ┆       ┆           │
│ 1        ┆ Roberts, Kenneth       ┆ jn19990007077 ┆ ["aut"]               ┆ … ┆ null      ┆ 1945 ┆ 498   ┆ pevná     │
│          ┆ Lewis,                 ┆               ┆                       ┆   ┆           ┆      ┆       ┆           │
│ 1        ┆ Ṣāliḥ, aṭ-Ṭajjib,      ┆ xx0030699     ┆ ["aut"]               ┆ … ┆ null      ┆ 1986 ┆ 157   ┆ brožovaná │
│ 1        ┆ Březina, Jan,          ┆ jk01020032    ┆ ["aut"]               ┆ … ┆ null      ┆ 1937 ┆ 126   ┆ null      │
└──────────┴────────────────────────┴───────────────┴───────────────────────┴───┴───────────┴──────┴───────┴───────────┘

In [50]:
aut = pl.read_parquet(os.path.join("data","aut_vyber.parquet"))

In [54]:
aut.explode(pl.col("100_a")).filter(pl.col("100_a").str.contains("Ṣāliḥ"))

shape: (5, 34)
┌───────────┬───────────┬───────────┬───────────┬───┬─────────────────┬────────────────┬────────────────┬──────────────┐
│ 024_2     ┆ 024_a     ┆ 046_f     ┆ 046_g     ┆ … ┆ 678_a           ┆ 856_u          ┆ leader         ┆ 001          │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---             ┆ ---            ┆ ---            ┆ ---          │
│ list[str] ┆ list[str] ┆ list[str] ┆ list[str] ┆   ┆ list[str]       ┆ list[str]      ┆ str            ┆ str          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═════════════════╪════════════════╪════════════════╪══════════════╡
│ null      ┆ null      ┆ ["1929"]  ┆ ["2009"]  ┆ … ┆ ["Súdánský      ┆ ["http://en.wi ┆ cz  a22     n  ┆ xx0030699    │
│           ┆           ┆           ┆           ┆   ┆ spisovatel a    ┆ kipedia.org/wi ┆ 4500           ┆              │
│           ┆           ┆           ┆           ┆   ┆ public…         ┆ ki…            ┆                ┆              │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ ["Politolog     ┆ null           ┆ nz  a22     n  ┆ jo2012688340 │
│           ┆           ┆           ┆           ┆   ┆ zaměřený na     ┆                ┆ 4500           ┆              │
│           ┆           ┆           ┆           ┆   ┆ oblast…         ┆                ┆                ┆              │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ ["Libanonská    ┆ null           ┆ cz  a22     n  ┆ jo2015895094 │
│           ┆           ┆           ┆           ┆   ┆ novinářka,      ┆                ┆ 4500           ┆              │
│           ┆           ┆           ┆           ┆   ┆ spisov…         ┆                ┆                ┆              │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ ["MSc., PhD.,   ┆ null           ┆ nz  a22     n  ┆ jo2016924996 │
│           ┆           ┆           ┆           ┆   ┆ vysokoškolská   ┆                ┆ 4500           ┆              │
│           ┆           ┆           ┆           ┆   ┆ pe…             ┆                ┆                ┆              │
│ null      ┆ null      ┆ null      ┆ null      ┆ … ┆ ["Lingvista,    ┆ null           ┆ nz  a22     n  ┆ jo2018986533 │
│           ┆           ┆           ┆           ┆   ┆ vysokoškolský   ┆                ┆ 4500           ┆              │
│           ┆           ┆           ┆           ┆   ┆ ped…            ┆                ┆                ┆              │
└───────────┴───────────┴───────────┴───────────┴───┴─────────────────┴────────────────┴────────────────┴──────────────┘

In [46]:
df.filter(pl.col("100_7").str.contains("xx0030699"))

shape: (1, 73)
┌──────────┬───────────────────┬───────────┬───────────┬───┬───────────┬──────┬───────┬───────────┐
│ 100_ind1 ┆ 100_a             ┆ 100_7     ┆ 100_4     ┆ … ┆ 700_g     ┆ rok  ┆ stran ┆ vazba     │
│ ---      ┆ ---               ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---  ┆ ---   ┆ ---       │
│ str      ┆ str               ┆ str       ┆ list[str] ┆   ┆ list[str] ┆ i64  ┆ i64   ┆ str       │
╞══════════╪═══════════════════╪═══════════╪═══════════╪═══╪═══════════╪══════╪═══════╪═══════════╡
│ 1        ┆ Ṣāliḥ, aṭ-Ṭajjib, ┆ xx0030699 ┆ ["aut"]   ┆ … ┆ null      ┆ 1986 ┆ 157   ┆ brožovaná │
└──────────┴───────────────────┴───────────┴───────────┴───┴───────────┴──────┴───────┴───────────┘